// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class AccountOpeningDview
{
    public string Accounts { get; set; }

    public string Voucher { get; set; }

    public decimal? TotalDebit { get; set; }

    public decimal? Credit { get; set; }

    public decimal? Debit { get; set; }

    public string Remarks { get; set; }

    public string Cheque { get; set; }

    public int? UserId { get; set; }

    public int PersonId { get; set; }
}