// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class AccountOpeningGraphView
{
    public string Accounts { get; set; }

    public int? Vyear { get; set; }

    public int? Vmonth { get; set; }

    public string VmonthName { get; set; }

    public decimal? TotalDebit { get; set; }

    public decimal? TotalCredit { get; set; }
}