// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class AccountOnRole
{
    public int RightsId { get; set; }

    public int? UserId { get; set; }

    public int? GroupId { get; set; }

    public int? AccountId { get; set; }

    public bool? Lock { get; set; }

    public virtual Chart Account { get; set; }

    public virtual User User { get; set; }
}