// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class AccountingEntry
{
    public int? Code { get; set; }

    public string VoucherNo { get; set; }

    public DateTime? Date { get; set; }

    public string ChqNo { get; set; }

    public DateTime? ChqDate { get; set; }

    public int? ChqStatus { get; set; }

    public int? AccountId { get; set; }

    public string Description { get; set; }

    public double? Debit { get; set; }

    public double? Credit { get; set; }

    public int? SeqNo { get; set; }

    public string InputType { get; set; }

    public string OppName { get; set; }

    public DateTime? CurrentDate { get; set; }

    public int Sorting { get; set; }

    public string TitleName { get; set; }

    public int? Posted { get; set; }

    public string DisPosted { get; set; }

    public int? DivisionId { get; set; }

    public string Division { get; set; }

    public int? DepartmentId { get; set; }

    public int? BookId { get; set; }

    public int? Description2 { get; set; }

    public int? FlockId { get; set; }

    public int? FlockName { get; set; }

    public int? VehicleNo { get; set; }

    public int? ItemName { get; set; }

    public int? Quantity { get; set; }

    public int? Pcs { get; set; }

    public int? Less { get; set; }

    public int? AvgWt { get; set; }

    public int? GrossWt { get; set; }

    public int? AdjWt { get; set; }

    public int? NetWt { get; set; }

    public int? Rate { get; set; }

    public DateTime? CreateDate { get; set; }
}