// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting.Models
{
    public partial class AccountOpeningVoucherResult
    {
        public int Code { get; set; }
        [StringLength(12)]
        public string RefNo { get; set; }
        public DateTime? Date { get; set; }
        public int? AccountID { get; set; }
        [StringLength(100)]
        public string AccountName { get; set; }
        [StringLength(2147483647)]
        public string Description { get; set; }
        [Column("Debit", TypeName = "money")]
        public decimal? Debit { get; set; }
        [Column("Credit", TypeName = "money")]
        public decimal? Credit { get; set; }
        public int SeqNo { get; set; }
        [StringLength(5)]
        public string InputType { get; set; }
        [StringLength(100)]
        public string DisplayCompany { get; set; }
    }
}
