// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class AccountOpeningM
{
    public int Id { get; set; }

    public DateTime? Vdate { get; set; }

    public string Remarks { get; set; }

    public int? BookCode { get; set; }

    public string VoucherNo { get; set; }

    public int Mcode { get; set; }

    public int CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public string Voucher { get; set; }

    public DateTime? UpdatedTime { get; set; }

    public virtual ICollection<AccountOpeningD> AccountOpeningDs { get; set; } = new List<AccountOpeningD>();

    public virtual Company Company { get; set; }

    public virtual User User { get; set; }
}