// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class App
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public byte? SeqNo { get; set; }

    public DateOnly? CurrentDate { get; set; }

    public int? UserId { get; set; }

    public string Label { get; set; }

    public string Icon { get; set; }

    public string Color { get; set; }

    public string FilePath { get; set; }

    public string FolderName { get; set; }

    public string Status { get; set; }

    public string Url { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<MainMenu> MainMenus { get; set; } = new List<MainMenu>();
}