// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Attachment
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int SeqNo { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public string Inputtype { get; set; }

    public byte[] ImageFile { get; set; }

    public string ImagePath { get; set; }
}