// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class AttendencePooling
{
    public int? Code { get; set; }

    public int? EmployeeId { get; set; }

    public int? PoolingType { get; set; }

    public DateTime? AttDateTime { get; set; }

    public DateOnly? AttDate { get; set; }

    public TimeOnly? AttTime { get; set; }

    public string MachineSerial { get; set; }
}