// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class BankReceiptD
{
    public int Id { get; set; }

    public int PersonId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? ChkDate { get; set; }

    public int? ActCode { get; set; }

    public string Remarks { get; set; }

    public string Cheque { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public string Po { get; set; }

    public int? BrecNo2 { get; set; }

    public int? BrecNo1 { get; set; }

    public string ManualNo { get; set; }

    public int? CostId { get; set; }

    public virtual Chart ActCodeNavigation { get; set; }

    public virtual BankReceiptM Person { get; set; }
}