// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class BankRecDview
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public decimal? Debit { get; set; }

    public decimal Credit { get; set; }

    public DateOnly? ChkDate { get; set; }

    public string Remarks { get; set; }

    public string Cheque { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public bool? Selected { get; set; }

    public bool? Posted { get; set; }

    public int? IrefId { get; set; }

    public string Iremarks { get; set; }

    public DateOnly? Vdate { get; set; }
}