// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class BankRecD
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public decimal? Debit { get; set; }

    public decimal Credit { get; set; }

    public DateOnly? ChkDate { get; set; }

    public string Remarks { get; set; }

    public string Cheque { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public bool? Selected { get; set; }

    public bool? Posted { get; set; }

    public int? IrefId { get; set; }

    public string Manual { get; set; }

    public string Po { get; set; }

    public int? TcompanyId { get; set; }

    public string IinputType { get; set; }

    public string Ivoucher { get; set; }

    public string Iremarks { get; set; }

    public string TableName { get; set; }

    public string FieldName { get; set; }

    public string RefCol { get; set; }

    public DateOnly? Vdate { get; set; }

    public virtual BankRecM Ref { get; set; }

    public virtual Company Tcompany { get; set; }
}