// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CashReceiptD
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int? AccountId { get; set; }

    public string Description { get; set; }

    public decimal? Amount { get; set; }

    public int? UserId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public virtual CashReceiptM Ref { get; set; }
}