// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CashPaymentD
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int? AccountId { get; set; }

    public string Description { get; set; }

    public decimal? Amount { get; set; }

    public virtual CashPaymentM Ref { get; set; }
}