// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CashReceiptM
{
    public int Id { get; set; }

    public int? PartyId { get; set; }

    public DateTime Date { get; set; }

    public string Note { get; set; }

    public decimal Subtotal { get; set; }

    public int RefNo { get; set; }

    public string InputType { get; set; }

    public int DivisionId { get; set; }

    public string InvoiceNumber { get; set; }

    public int? UserId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public virtual ICollection<CashReceiptD> CashReceiptDs { get; set; } = new List<CashReceiptD>();
}