// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CashPaymentDview
{
    public int Id { get; set; }

    public int Refid { get; set; }

    public string Description { get; set; }

    public string AccountName { get; set; }

    public decimal? Amount { get; set; }
}