// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CashPaymentMview
{
    public int Id { get; set; }

    public DateOnly? IssuedDate { get; set; }

    public string Clientname { get; set; }

    public decimal Total { get; set; }

    public decimal Balance { get; set; }

    public DateOnly? DueDate { get; set; }

    public string InvoiceNumber { get; set; }

    public string Prefix { get; set; }

    public int Action { get; set; }
}