// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CashPaymentM
{
    public int Id { get; set; }

    public string InvoiceNumber { get; set; }

    public int? PartyId { get; set; }

    public DateTime Date { get; set; }

    public string Note { get; set; }

    public decimal Subtotal { get; set; }

    public int RefNo { get; set; }

    public string InputType { get; set; }

    public int DivisionId { get; set; }

    public virtual ICollection<CashPaymentD> CashPaymentDs { get; set; } = new List<CashPaymentD>();

    public virtual Company Division { get; set; }
}