// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Category
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public int? InvactId { get; set; }

    public int? WipactId { get; set; }

    public int? CosactId { get; set; }

    public int? SlactId { get; set; }

    public int? SlractId { get; set; }

    public int? NatureId { get; set; }

    public int? Type { get; set; }
}