// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CbookM
{
    public int Id { get; set; }

    public DateOnly? Vdate { get; set; }

    public string Remarks { get; set; }

    public int? BookCode { get; set; }

    public string VoucherNo { get; set; }

    public int Mcode { get; set; }

    public string Voucher { get; set; }

    public int CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public bool Posted { get; set; }

    public virtual Chart BookCodeNavigation { get; set; }

    public virtual ICollection<CbookD> CbookDs { get; set; } = new List<CbookD>();

    public virtual Company Company { get; set; }

    public virtual User User { get; set; }
}