// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CbookVoucher
{
    public int Code { get; set; }

    public string RefNo { get; set; }

    public DateOnly? Date { get; set; }

    public int? BookId { get; set; }

    public string BookName { get; set; }

    public string ChqNo { get; set; }

    public DateOnly? ChqDate { get; set; }

    public int? AccountId { get; set; }

    public string AccountName { get; set; }

    public string Description { get; set; }

    public decimal? Amount { get; set; }

    public int SeqNo { get; set; }

    public string InputType { get; set; }

    public string DisplayCompany { get; set; }
}