// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CbookDview
{
    public int Id { get; set; }

    public int PersonId { get; set; }

    public decimal Amount { get; set; }

    public DateOnly? ChkDate { get; set; }

    public int? ActCode { get; set; }

    public string Remarks { get; set; }

    public string Cheque { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? CostId { get; set; }

    public string Accounts { get; set; }

    public string CostCenterName { get; set; }
}