// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Chart
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Descript { get; set; }

    public string Name2 { get; set; }

    public int? NatureId { get; set; }

    public int? GroupId { get; set; }

    public int? TypeId { get; set; }

    public string NatureName { get; set; }

    public string TypeName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Ntnno { get; set; }

    public string Gstno { get; set; }

    public int? UserId { get; set; }

    public decimal Whperc { get; set; }

    public int? SpersonId { get; set; }

    public virtual ICollection<AccountOnRole> AccountOnRoles { get; set; } = new List<AccountOnRole>();

    public virtual ICollection<BbookD> BbookDs { get; set; } = new List<BbookD>();

    public virtual ICollection<BbookM> BbookMs { get; set; } = new List<BbookM>();

    public virtual ICollection<BookType> BookTypes { get; set; } = new List<BookType>();

    public virtual ICollection<CashSlipD> CashSlipDs { get; set; } = new List<CashSlipD>();

    public virtual ICollection<CashSlipM> CashSlipMs { get; set; } = new List<CashSlipM>();

    public virtual ICollection<CbookD> CbookDs { get; set; } = new List<CbookD>();

    public virtual ICollection<CbookM> CbookMs { get; set; } = new List<CbookM>();

    public virtual ICollection<ChequeD> ChequeDActCodeNavigations { get; set; } = new List<ChequeD>();

    public virtual ICollection<ChequeD> ChequeDBookCodeNavigations { get; set; } = new List<ChequeD>();

    public virtual ICollection<CostSheetD2> CostSheetD2s { get; set; } = new List<CostSheetD2>();

    public virtual ICollection<CostSheetM> CostSheetMs { get; set; } = new List<CostSheetM>();

    public virtual ICollection<Dropdown> Dropdowns { get; set; } = new List<Dropdown>();

    public virtual ICollection<FdchallanM> FdchallanMs { get; set; } = new List<FdchallanM>();

    public virtual ICollection<FocinvoiceM> FocinvoiceMParties { get; set; } = new List<FocinvoiceM>();

    public virtual ICollection<FocinvoiceM> FocinvoiceMSpeople { get; set; } = new List<FocinvoiceM>();

    public virtual ICollection<FpinvoiceM> FpinvoiceMs { get; set; } = new List<FpinvoiceM>();

    public virtual ICollection<GatePassD> GatePassDs { get; set; } = new List<GatePassD>();

    public virtual ICollection<GmultiD> GmultiDs { get; set; } = new List<GmultiD>();

    public virtual ICollection<GmultiM> GmultiMs { get; set; } = new List<GmultiM>();

    public virtual ICollection<IssOutM> IssOutMs { get; set; } = new List<IssOutM>();

    public virtual ICollection<JorderM> JorderMs { get; set; } = new List<JorderM>();

    public virtual ICollection<LoanIssueM> LoanIssueMs { get; set; } = new List<LoanIssueM>();

    public virtual ICollection<LoanRecD> LoanRecDs { get; set; } = new List<LoanRecD>();

    public virtual ICollection<LoanRecM> LoanRecMs { get; set; } = new List<LoanRecM>();

    public virtual ChartActType Nature { get; set; }

    public virtual ICollection<OwnerEquity> OwnerEquityCapitals { get; set; } = new List<OwnerEquity>();

    public virtual ICollection<OwnerEquity> OwnerEquityDrawings { get; set; } = new List<OwnerEquity>();

    public virtual ICollection<OwnerEquity> OwnerEquityInvestments { get; set; } = new List<OwnerEquity>();

    public virtual ICollection<PayEmFullLoanM> PayEmFullLoanMs { get; set; } = new List<PayEmFullLoanM>();

    public virtual ICollection<PayEmployeAdvanceM> PayEmployeAdvanceMs { get; set; } = new List<PayEmployeAdvanceM>();

    public virtual ICollection<PayEmployeLoanAdM> PayEmployeLoanAdMs { get; set; } = new List<PayEmployeLoanAdM>();

    public virtual ICollection<PayEmployeLoanM> PayEmployeLoanMs { get; set; } = new List<PayEmployeLoanM>();

    public virtual ICollection<PaymentD2> PaymentD2s { get; set; } = new List<PaymentD2>();

    public virtual ICollection<PinvoiceM> PinvoiceMs { get; set; } = new List<PinvoiceM>();

    public virtual ICollection<PorderM> PorderMs { get; set; } = new List<PorderM>();

    public virtual ICollection<PreturnM> PreturnMs { get; set; } = new List<PreturnM>();

    public virtual ICollection<RbookM> RbookMs { get; set; } = new List<RbookM>();

    public virtual ICollection<RchallanM> RchallanMs { get; set; } = new List<RchallanM>();

    public virtual ICollection<RecOutM> RecOutMs { get; set; } = new List<RecOutM>();

    public virtual ICollection<ReceiptD2> ReceiptD2s { get; set; } = new List<ReceiptD2>();

    public virtual ICollection<RecevM> RecevMs { get; set; } = new List<RecevM>();

    public virtual ICollection<RoleName> RoleNames { get; set; } = new List<RoleName>();

    public virtual ICollection<SbookM> SbookMs { get; set; } = new List<SbookM>();

    public virtual ICollection<SorderM> SorderMs { get; set; } = new List<SorderM>();

    public virtual ICollection<SreturnM> SreturnMs { get; set; } = new List<SreturnM>();

    public virtual ICollection<StaxInvD2> StaxInvD2s { get; set; } = new List<StaxInvD2>();

    public virtual ICollection<TbookD> TbookDs { get; set; } = new List<TbookD>();

    public virtual ICollection<TbookM> TbookMs { get; set; } = new List<TbookM>();

    public virtual Dropdown Type { get; set; }

    public virtual User User { get; set; }
}