// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Chart
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Descript { get; set; }

    public string Name2 { get; set; }

    public int? NatureId { get; set; }

    public int? GroupId { get; set; }

    public int? TypeId { get; set; }

    public string NatureName { get; set; }

    public string TypeName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Ntnno { get; set; }

    public string Gstno { get; set; }

    public int? UserId { get; set; }

    public decimal Whperc { get; set; }

    public int? SpersonId { get; set; }

    public int CrDays { get; set; }

    public decimal Gstperc { get; set; }

    public decimal Fstperc { get; set; }

    public virtual ICollection<BankPaymentD> BankPaymentDs { get; set; } = new List<BankPaymentD>();

    public virtual ICollection<BankPaymentM> BankPaymentMs { get; set; } = new List<BankPaymentM>();

    public virtual ICollection<BankReceiptD> BankReceiptDs { get; set; } = new List<BankReceiptD>();

    public virtual ICollection<BankReceiptM> BankReceiptMs { get; set; } = new List<BankReceiptM>();

    public virtual ICollection<CashPaymentD> CashPaymentDs { get; set; } = new List<CashPaymentD>();

    public virtual ICollection<CashPaymentM> CashPaymentMs { get; set; } = new List<CashPaymentM>();

    public virtual ICollection<Dropdown> Dropdowns { get; set; } = new List<Dropdown>();

    public virtual ICollection<GjournalD> GjournalDs { get; set; } = new List<GjournalD>();

    public virtual ICollection<GjournalM> GjournalMs { get; set; } = new List<GjournalM>();

    public virtual ICollection<PinvoiceM> PinvoiceMs { get; set; } = new List<PinvoiceM>();

    public virtual User User { get; set; }
}