// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ChartActType
{
    public int RefNo { get; set; }

    public int? Gptype { get; set; }

    public int? Type { get; set; }

    public string Name { get; set; }

    public string HeaderName { get; set; }

    public string HeaderName2 { get; set; }

    public int? AccountType1 { get; set; }

    public int? AccountType2 { get; set; }

    public byte? PageNo { get; set; }

    public virtual ICollection<Chart> Charts { get; set; } = new List<Chart>();
}