// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ChequeD
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public decimal Amount { get; set; }

    public DateOnly? ChkDate { get; set; }

    public int? ActCode { get; set; }

    public string Remarks { get; set; }

    public string Cheque { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? BookCode { get; set; }

    public bool? Selected { get; set; }

    public bool? Posted { get; set; }

    public int? IrefId { get; set; }

    public string Manual { get; set; }

    public string Po { get; set; }

    public int? TcompanyId { get; set; }

    public string IinputType { get; set; }

    public string Ivoucher { get; set; }

    public string Iremarks { get; set; }

    public int? BrecNo1 { get; set; }

    public int? BrecNo2 { get; set; }

    public int? FavorId { get; set; }

    public int? Imcode { get; set; }

    public decimal Igamount { get; set; }

    public virtual Chart ActCodeNavigation { get; set; }

    public virtual Chart BookCodeNavigation { get; set; }

    public virtual Favor Favor { get; set; }

    public virtual ChequeM Ref { get; set; }

    public virtual Company Tcompany { get; set; }
}