// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ChequeM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int Mcode { get; set; }

    public string Voucher { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public DateOnly? Fdate { get; set; }

    public DateOnly? Tdate { get; set; }

    public virtual ICollection<ChequeD> ChequeDs { get; set; } = new List<ChequeD>();

    public virtual Company Company { get; set; }

    public virtual User User { get; set; }
}