// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CityCountryView
{
    public int Id { get; set; }

    public string City { get; set; }

    public string Countryname { get; set; }

    public bool? Citystatus { get; set; }

    public bool? Countrystatus { get; set; }
}