// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ClosingYear
{
    public int Id { get; set; }

    public DateTime? ClosingDate { get; set; }
}