// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Company
{
    public int Code { get; set; }

    public string ManCode { get; set; }

    public string Name { get; set; }

    public bool? Status { get; set; }

    public string Note { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Ntnno { get; set; }

    public string Gstno { get; set; }

    public byte? AgedCol11 { get; set; }

    public byte? AgedCol12 { get; set; }

    public string AgedColH1 { get; set; }

    public byte? AgedCol21 { get; set; }

    public byte? AgedCol22 { get; set; }

    public string AgedColH2 { get; set; }

    public byte? AgedCol31 { get; set; }

    public byte? AgedCol32 { get; set; }

    public string AgedColH3 { get; set; }

    public string AgedColH4 { get; set; }

    public byte? CompanyType { get; set; }

    public string Prefix { get; set; }

    public int? StaxAccountId { get; set; }

    public int? WtaxAccountId { get; set; }

    public int? WgtaxAccountId { get; set; }

    public int? Rloan { get; set; }

    public int? Ploan { get; set; }

    public virtual ICollection<BankRecD> BankRecDs { get; set; } = new List<BankRecD>();

    public virtual ICollection<BankRecM> BankRecMs { get; set; } = new List<BankRecM>();

    public virtual ICollection<BbookM> BbookMs { get; set; } = new List<BbookM>();

    public virtual ICollection<CashSlipM> CashSlipMs { get; set; } = new List<CashSlipM>();

    public virtual ICollection<CbookM> CbookMs { get; set; } = new List<CbookM>();

    public virtual ICollection<ChequeD> ChequeDs { get; set; } = new List<ChequeD>();

    public virtual ICollection<ChequeM> ChequeMs { get; set; } = new List<ChequeM>();

    public virtual ICollection<CostSheetM> CostSheetMs { get; set; } = new List<CostSheetM>();

    public virtual ICollection<DchallanM> DchallanMs { get; set; } = new List<DchallanM>();

    public virtual ICollection<FdchallanM> FdchallanMs { get; set; } = new List<FdchallanM>();

    public virtual ICollection<FocinvoiceM> FocinvoiceMs { get; set; } = new List<FocinvoiceM>();

    public virtual ICollection<FoinvoiceM> FoinvoiceMs { get; set; } = new List<FoinvoiceM>();

    public virtual ICollection<FpinvoiceM> FpinvoiceMs { get; set; } = new List<FpinvoiceM>();

    public virtual ICollection<GatePassM> GatePassMs { get; set; } = new List<GatePassM>();

    public virtual ICollection<GmultiM> GmultiMs { get; set; } = new List<GmultiM>();

    public virtual ICollection<InvAdjustM> InvAdjustMs { get; set; } = new List<InvAdjustM>();

    public virtual ICollection<IopeningM> IopeningMs { get; set; } = new List<IopeningM>();

    public virtual ICollection<IssOutM> IssOutMs { get; set; } = new List<IssOutM>();

    public virtual ICollection<IssueM> IssueMs { get; set; } = new List<IssueM>();

    public virtual ICollection<JorderM> JorderMs { get; set; } = new List<JorderM>();

    public virtual ICollection<LoanIssueM> LoanIssueMs { get; set; } = new List<LoanIssueM>();

    public virtual ICollection<LoanRecD> LoanRecDs { get; set; } = new List<LoanRecD>();

    public virtual ICollection<LoanRecM> LoanRecMs { get; set; } = new List<LoanRecM>();

    public virtual ICollection<OwnerEquity> OwnerEquities { get; set; } = new List<OwnerEquity>();

    public virtual ICollection<PayClassM> PayClassMs { get; set; } = new List<PayClassM>();

    public virtual ICollection<PayEmployeAdvanceM> PayEmployeAdvanceMs { get; set; } = new List<PayEmployeAdvanceM>();

    public virtual ICollection<PayEmployeLoanAdM> PayEmployeLoanAdMs { get; set; } = new List<PayEmployeLoanAdM>();

    public virtual ICollection<PayEmployeLoanM> PayEmployeLoanMs { get; set; } = new List<PayEmployeLoanM>();

    public virtual ICollection<PaySalaryD> PaySalaryDs { get; set; } = new List<PaySalaryD>();

    public virtual ICollection<PinvoiceM> PinvoiceMs { get; set; } = new List<PinvoiceM>();

    public virtual ICollection<PorderM> PorderMs { get; set; } = new List<PorderM>();

    public virtual ICollection<PreturnM> PreturnMs { get; set; } = new List<PreturnM>();

    public virtual ICollection<ProcessM> ProcessMs { get; set; } = new List<ProcessM>();

    public virtual ICollection<PtargetM> PtargetMs { get; set; } = new List<PtargetM>();

    public virtual ICollection<RbookM> RbookMs { get; set; } = new List<RbookM>();

    public virtual ICollection<RchallanM> RchallanMs { get; set; } = new List<RchallanM>();

    public virtual ICollection<RecFinishM> RecFinishMs { get; set; } = new List<RecFinishM>();

    public virtual ICollection<RecOutM> RecOutMs { get; set; } = new List<RecOutM>();

    public virtual ICollection<RecevM> RecevMs { get; set; } = new List<RecevM>();

    public virtual ICollection<SbookM> SbookMs { get; set; } = new List<SbookM>();

    public virtual ICollection<SinvoiceM> SinvoiceMs { get; set; } = new List<SinvoiceM>();

    public virtual ICollection<SorderM> SorderMs { get; set; } = new List<SorderM>();

    public virtual ICollection<SreturnM> SreturnMs { get; set; } = new List<SreturnM>();

    public virtual ICollection<StaxInvM> StaxInvMs { get; set; } = new List<StaxInvM>();

    public virtual ICollection<TbookM> TbookMs { get; set; } = new List<TbookM>();
}