// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Company
{
    public int Code { get; set; }

    public string ManCode { get; set; }

    public string Name { get; set; }

    public bool? Status { get; set; }

    public string Note { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Ntnno { get; set; }

    public string Gstno { get; set; }

    public byte? AgedCol11 { get; set; }

    public byte? AgedCol12 { get; set; }

    public string AgedColH1 { get; set; }

    public byte? AgedCol21 { get; set; }

    public byte? AgedCol22 { get; set; }

    public string AgedColH2 { get; set; }

    public byte? AgedCol31 { get; set; }

    public byte? AgedCol32 { get; set; }

    public string AgedColH3 { get; set; }

    public string AgedColH4 { get; set; }

    public byte? CompanyType { get; set; }

    public string Prefix { get; set; }

    public int? StaxAccountId { get; set; }

    public int? WtaxAccountId { get; set; }

    public int? WgtaxAccountId { get; set; }

    public int? Rloan { get; set; }

    public int? Ploan { get; set; }

    public string Fbrurl { get; set; }

    public string Fbrauth { get; set; }

    public long? Posid { get; set; }

    public string Usin { get; set; }

    public string Company1 { get; set; }

    public string Branch { get; set; }

    public int? BranchRecId { get; set; }

    public int? BranchPayId { get; set; }

    public string Remarks { get; set; }

    public virtual ICollection<AccountOpeningM> AccountOpeningMs { get; set; } = new List<AccountOpeningM>();

    public virtual ICollection<BankPaymentM> BankPaymentMs { get; set; } = new List<BankPaymentM>();

    public virtual ICollection<BankReceiptM> BankReceiptMs { get; set; } = new List<BankReceiptM>();

    public virtual ICollection<CashPaymentM> CashPaymentMs { get; set; } = new List<CashPaymentM>();

    public virtual ICollection<GjournalM> GjournalMs { get; set; } = new List<GjournalM>();
}