// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CostExp
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public bool AlwaysCharge { get; set; }

    public bool CombineGv { get; set; }

    public int? GlactId { get; set; }

    public virtual ICollection<CostSheetD2> CostSheetD2s { get; set; } = new List<CostSheetD2>();
}