// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CostSheetDview
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int ItemId { get; set; }

    public decimal Quantity { get; set; }

    public double Rate { get; set; }

    public double? Amount { get; set; }

    public string Remarks { get; set; }

    public int LocationId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? IrefId { get; set; }

    public int? IrefSeq { get; set; }

    public int? BrandId { get; set; }

    public int? QualityId { get; set; }

    public int? SizeId { get; set; }

    public decimal? Packing { get; set; }

    public decimal? Pcs { get; set; }

    public string Unit { get; set; }

    public decimal Tax { get; set; }

    public double? TaxAmount { get; set; }

    public double? NetAmount { get; set; }

    public decimal Whtax { get; set; }

    public double? WhTaxAmount { get; set; }

    public double LessWhAmt { get; set; }

    public string ItemName { get; set; }

    public string LocationName { get; set; }

    public string Ivoucher { get; set; }

    public decimal? Irate { get; set; }

    public decimal? DiscRate { get; set; }

    public decimal? DiscAmt { get; set; }

    public string LotNo { get; set; }

    public string Grade { get; set; }

    public string ReferenceNo { get; set; }

    public decimal PerLbswt { get; set; }

    public decimal? Kg { get; set; }

    public double? CostRate { get; set; }

    public int? UnitId { get; set; }
}