// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CostSheetM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int? PartyId { get; set; }

    public int RefNo { get; set; }

    public string DrefNo { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public int? RefId { get; set; }

    public string PrefNo { get; set; }

    public decimal? AdvanceBal { get; set; }

    public decimal? AdvancePaid { get; set; }

    public int CrDays { get; set; }

    public int? CommId { get; set; }

    public decimal CommPerc { get; set; }

    public decimal CommAmt { get; set; }

    public decimal? Ocharges { get; set; }

    public decimal ScommPerc { get; set; }

    public decimal ScommAmt { get; set; }

    public DateOnly Bedate { get; set; }

    public decimal ExRate { get; set; }

    public int? BankId { get; set; }

    public int? ExporterId { get; set; }

    public bool Approved { get; set; }

    public bool Rejected { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<CostSheetD2> CostSheetD2s { get; set; } = new List<CostSheetD2>();

    public virtual ICollection<CostSheetD> CostSheetDs { get; set; } = new List<CostSheetD>();

    public virtual Chart Party { get; set; }

    public virtual User User { get; set; }
}