// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CostSheetD2
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public DateOnly? Date { get; set; }

    public int? CostExpId { get; set; }

    public int? GlactId { get; set; }

    public decimal Amount { get; set; }

    public string Remarks { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public virtual CostExp CostExp { get; set; }

    public virtual Chart Glact { get; set; }

    public virtual CostSheetM Ref { get; set; }
}