// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class CostSheetD
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int ItemId { get; set; }

    public decimal Quantity { get; set; }

    public double Rate { get; set; }

    public double? Amount { get; set; }

    public string Remarks { get; set; }

    public int LocationId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? IrefId { get; set; }

    public int? IrefSeq { get; set; }

    public int? BrandId { get; set; }

    public int? QualityId { get; set; }

    public int? SizeId { get; set; }

    public decimal? Packing { get; set; }

    public decimal? Pcs { get; set; }

    public string Unit { get; set; }

    public decimal? Tax { get; set; }

    public double? TaxAmount { get; set; }

    public double? NetAmount { get; set; }

    public decimal? Whtax { get; set; }

    public double? WhTaxAmount { get; set; }

    public decimal? LessWhAmt { get; set; }

    public decimal? Irate { get; set; }

    public decimal? GstRate { get; set; }

    public decimal? LessWhAmt2 { get; set; }

    public decimal PerLbswt { get; set; }

    public string LotNo { get; set; }

    public string Grade { get; set; }

    public string ReferenceNo { get; set; }

    public decimal? Kg { get; set; }

    public double? ExpRate { get; set; }

    public decimal? ExRate { get; set; }

    public double? CostRate { get; set; }

    public double? NcostRate { get; set; }

    public int? UnitId { get; set; }

    public virtual Item Item { get; set; }

    public virtual Location Location { get; set; }

    public virtual CostSheetM Ref { get; set; }
}