// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting.Models
{
    public partial class CustomerProfileReportResult
    {
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(100)]
        public string SPerson { get; set; }
        [StringLength(500)]
        public string Address { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Fax { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(300)]
        public string Descript { get; set; }
        [StringLength(50)]
        public string NTNNo { get; set; }
        [StringLength(100)]
        public string GroupName { get; set; }
        [StringLength(50)]
        public string Nature { get; set; }
    }
}
