// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Customer
{
    public int Id { get; set; }

    public bool? Status { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Description { get; set; }

    public string IdentityNo { get; set; }

    public string Strno { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string Address3 { get; set; }

    public string Province { get; set; }

    public string Phone { get; set; }

    public string Mobile { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public int? CityId { get; set; }
}