// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Default
{
    public int Id { get; set; }

    public int? PurTaxId { get; set; }

    public int? SalTaxId { get; set; }

    public int? FsalTaxId { get; set; }

    public int? PurWhTaxId { get; set; }

    public int? WhtaxId { get; set; }

    public int? SaleDiscId { get; set; }

    public int? FreightId { get; set; }

    public string Remarks { get; set; }

    public decimal? IncomeTax { get; set; }

    public int? ExtraId { get; set; }

    public int? ExtraId2 { get; set; }

    public decimal? Whtax { get; set; }
}