// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class DefaultAccount
{
    public int Id { get; set; }

    public int? RefId { get; set; }

    public int? GroupId { get; set; }

    public byte? DisplayType { get; set; }
}