// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class DefaultsView
{
    public int Id { get; set; }

    public string Remarks { get; set; }

    public string Invname { get; set; }

    public string Wipname { get; set; }

    public string Cosname { get; set; }

    public string Slname { get; set; }

    public string Slrname { get; set; }

    public decimal? IncomeTax { get; set; }

    public string SaleDiscName { get; set; }

    public string FreightName { get; set; }
}