// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class DepRatio
{
    public int Id { get; set; }

    public string Inputtype { get; set; }

    public int Code { get; set; }

    public int SeqNo { get; set; }

    public int RowNum { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime CurrentDateTime { get; set; }

    public int? MonthDiff { get; set; }

    public decimal? Amount { get; set; }

    public decimal? DepAmount { get; set; }

    public decimal? Balance { get; set; }

    public byte? Posted { get; set; }

    public int? AccountId { get; set; }

    public int? AccountId2 { get; set; }

    public int? CompanyId { get; set; }
}