// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class DesignComponent
{
    public int Id { get; set; }

    public int DesignId { get; set; }

    public string ComponentType { get; set; }

    public string Properties { get; set; }

    public int PositionX { get; set; }

    public int PositionY { get; set; }

    public int Order { get; set; }

    public virtual Design Design { get; set; }
}