// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class EmployeeLeaveDetail
{
    public int? LeaveId { get; set; }

    public DateTime? LeaveDate { get; set; }

    public int? LeaveCheck { get; set; }
}