// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class FcategoryView
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public string Invname { get; set; }

    public string Wipname { get; set; }

    public string Cosname { get; set; }

    public string Slname { get; set; }

    public string Slrname { get; set; }

    public string Invtitle { get; set; }

    public string Wiptitle { get; set; }

    public string Costitle { get; set; }

    public string Sltitle { get; set; }

    public string Slrtitle { get; set; }
}