// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class FdchallanDview
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int ItemId { get; set; }

    public decimal Quantity { get; set; }

    public decimal Rate { get; set; }

    public decimal? Amount { get; set; }

    public string Remarks { get; set; }

    public int LocationId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? IrefId { get; set; }

    public int? IrefSeq { get; set; }

    public decimal? CostRate { get; set; }

    public decimal Packing { get; set; }

    public decimal Pcs { get; set; }

    public string Unit { get; set; }

    public string CInputtype { get; set; }

    public int? CRefId { get; set; }

    public int? CRefSeq { get; set; }

    public int? ContractId { get; set; }

    public int? JobId { get; set; }

    public string Brand { get; set; }

    public string Quality { get; set; }

    public string Modal { get; set; }

    public string Serial { get; set; }

    public decimal Tax { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? NetAmount { get; set; }

    public string ItemName { get; set; }

    public string LocationName { get; set; }
}