// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Fitem
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public int? CategoryId { get; set; }

    public int LocationId { get; set; }

    public int? UnitId { get; set; }

    public decimal Packing { get; set; }

    public virtual Fcategory Category { get; set; }

    public virtual ICollection<FdchallanD> FdchallanDs { get; set; } = new List<FdchallanD>();

    public virtual ICollection<FoinvoiceD> FoinvoiceDs { get; set; } = new List<FoinvoiceD>();

    public virtual ICollection<FpinvoiceD> FpinvoiceDs { get; set; } = new List<FpinvoiceD>();
}