// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class FocinvoiceDview
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int ItemId { get; set; }

    public decimal Quantity { get; set; }

    public string QuantityCompact { get; set; }

    public decimal Rate { get; set; }

    public string RateCompact { get; set; }

    public decimal? Amount { get; set; }

    public string AmountCompact { get; set; }

    public string TamountCompact { get; set; }

    public string Remarks { get; set; }

    public int LocationId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? IrefId { get; set; }

    public int? IrefSeq { get; set; }

    public decimal? CostRate { get; set; }

    public int? BrandId { get; set; }

    public int? QualityId { get; set; }

    public int? SizeId { get; set; }

    public decimal Packing { get; set; }

    public decimal Pcs { get; set; }

    public string Unit { get; set; }

    public decimal Tax { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? NetAmount { get; set; }

    public decimal Whtax { get; set; }

    public decimal? WhTaxAmount { get; set; }

    public decimal LessWhAmt { get; set; }

    public string ItemName { get; set; }

    public string LocationName { get; set; }

    public string Ivoucher { get; set; }

    public decimal Fgst { get; set; }

    public decimal? FgstAmount { get; set; }

    public string ItemName2 { get; set; }

    public string DueAmountCompact { get; set; }

    public string TamountCompactWocurr { get; set; }

    public string DueAmountCompactWocurr { get; set; }

    public decimal? PcsRet { get; set; }

    public int? ShopId { get; set; }

    public string ShopName { get; set; }
}