// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class FocinvoiceD
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int ItemId { get; set; }

    public decimal Quantity { get; set; }

    public decimal Rate { get; set; }

    public decimal? Amount { get; set; }

    public string Remarks { get; set; }

    public int LocationId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? IrefId { get; set; }

    public int? IrefSeq { get; set; }

    public decimal? CostRate { get; set; }

    public int? BrandId { get; set; }

    public int? QualityId { get; set; }

    public int? SizeId { get; set; }

    public decimal Packing { get; set; }

    public decimal Pcs { get; set; }

    public string Unit { get; set; }

    public decimal Tax { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? NetAmount { get; set; }

    public decimal? Whtax { get; set; }

    public decimal? WhTaxAmount { get; set; }

    public decimal? LessWhAmt { get; set; }

    public decimal? Fgst { get; set; }

    public decimal? FgstAmount { get; set; }

    public int? UnitId { get; set; }

    public bool IsActive { get; set; }

    public decimal? PcsRet { get; set; }

    public int? ShopId { get; set; }

    public virtual DchallanM Iref { get; set; }

    public virtual DchallanD IrefSeqNavigation { get; set; }

    public virtual Item Item { get; set; }

    public virtual Location Location { get; set; }

    public virtual FocinvoiceM Ref { get; set; }
}