// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class FocinvoiceM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int? PartyId { get; set; }

    public int RefNo { get; set; }

    public string DrefNo { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public int? RefId { get; set; }

    public decimal? Freight { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Mwhtax { get; set; }

    public int SpersonId { get; set; }

    public decimal? AdvanceBal { get; set; }

    public decimal? AdvancePaid { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<FocinvoiceD> FocinvoiceDs { get; set; } = new List<FocinvoiceD>();

    public virtual Chart Party { get; set; }

    public virtual Chart Sperson { get; set; }

    public virtual User User { get; set; }
}