// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class FormDatum
{
    public int Id { get; set; }

    public int FormId { get; set; }

    public string FieldName { get; set; }

    public string FieldValue { get; set; }

    public DateTime? CreatedAt { get; set; }
}