// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class FormField
{
    public int Id { get; set; }

    public int? FormId { get; set; }

    public string FieldName { get; set; }

    public string LabelName { get; set; }

    public string DataType { get; set; }

    public virtual FormDefinition Form { get; set; }
}