// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting.Models
{
    public partial class GetAccountOpeningReportDataResult
    {
        public int Id { get; set; }
        [StringLength(10)]
        public string Date { get; set; }
        [StringLength(2147483647)]
        public string MasterRemarks { get; set; }
        public int? BookCode { get; set; }
        [StringLength(100)]
        public string Companyname { get; set; }
        [StringLength(20)]
        public string VoucherNo { get; set; }
        public int? MCode { get; set; }
        public int Amount { get; set; }
        [StringLength(12)]
        public string Voucher { get; set; }
        public int CompanyID { get; set; }
        [StringLength(100)]
        public string Book { get; set; }
        [Column("MasterDebit", TypeName = "money")]
        public decimal? MasterDebit { get; set; }
        [Column("MasterCredit", TypeName = "money")]
        public decimal? MasterCredit { get; set; }
        public int? TotalSeqNo { get; set; }
        [StringLength(5)]
        public string InputType { get; set; }
        [StringLength(8)]
        public string MasterAccounts { get; set; }
        [StringLength(10)]
        public string Prefix { get; set; }
        [StringLength(100)]
        public string LedgerName { get; set; }
        [Column("TotalDebit", TypeName = "money")]
        public decimal? TotalDebit { get; set; }
        [Column("DetailCredit", TypeName = "money")]
        public decimal? DetailCredit { get; set; }
        [Column("DetailDebit", TypeName = "money")]
        public decimal? DetailDebit { get; set; }
        [StringLength(2147483647)]
        public string DetailRemarks { get; set; }
        [StringLength(50)]
        public string Cheque { get; set; }
        public int? UserID { get; set; }
        public int PersonID { get; set; }
    }
}
