// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting.Models
{
    public partial class GetAllAccountsAllSubGroupResult
    {
        public int? ID { get; set; }
        [StringLength(1000)]
        public string Name { get; set; }
        [StringLength(100)]
        public string Name2 { get; set; }
        [StringLength(300)]
        public string Descript { get; set; }
        public int? NatureID { get; set; }
        public int? GroupID { get; set; }
        public int? TypeID { get; set; }
        [StringLength(500)]
        public string Address { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Fax { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(50)]
        public string NTNNO { get; set; }
        [StringLength(50)]
        public string GSTNO { get; set; }
        public int? SPersonID { get; set; }
        [StringLength(50)]
        public string NatureName { get; set; }
        [StringLength(50)]
        public string TypeName { get; set; }
        [StringLength(100)]
        public string SPersonName { get; set; }
    }
}
