// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting.Models
{
    public partial class getdumpdataliveResult
    {
        public int result { get; set; }
        [StringLength(119)]
        public string Msg { get; set; }
    }
}
