// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting.Models
{
    public partial class GetMenuItemResult
    {
        public int id { get; set; }
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(200)]
        public string url { get; set; }
        [StringLength(200)]
        public string icon { get; set; }
        public byte? seqno { get; set; }
        [StringLength(200)]
        public string subname { get; set; }
        [StringLength(200)]
        public string nameclass { get; set; }
        public int? ParentID { get; set; }
    }
}
