// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting.Models
{
    public partial class GetSubMenuItemResult
    {
        public int id { get; set; }
        [StringLength(50)]
        public string name { get; set; }
        public int? moduleid { get; set; }
        [StringLength(50)]
        public string controller { get; set; }
        [StringLength(50)]
        public string action { get; set; }
        public byte? sort { get; set; }
        [StringLength(100)]
        public string subnameclass { get; set; }
        [StringLength(2147483647)]
        public string namelink { get; set; }
        [StringLength(2147483647)]
        public string target { get; set; }
        [StringLength(200)]
        public string nameclass { get; set; }
        public int? menuid { get; set; }
        [StringLength(50)]
        public string Apiaction { get; set; }
        public int IsApi { get; set; }
        [StringLength(2147483647)]
        public string CreateMessage { get; set; }
        [StringLength(2147483647)]
        public string UpdateMessage { get; set; }
        [StringLength(2147483647)]
        public string RemoveMessage { get; set; }
        [StringLength(50)]
        public string Apicontroller { get; set; }
    }
}
