// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Gjouranlview
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int? BookCode { get; set; }

    public string VoucherNo { get; set; }

    public int? Mcode { get; set; }

    public string Voucher { get; set; }

    public int CompanyId { get; set; }

    public string Book { get; set; }

    public decimal? Debit { get; set; }

    public decimal? Credit { get; set; }

    public int? TotalSeqNo { get; set; }

    public string InputType { get; set; }
}