// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class IadvanceEntry
{
    public int Code { get; set; }

    public string InputType { get; set; }

    public int? DivisionId { get; set; }

    public int? RefNo { get; set; }

    public DateTime? Date { get; set; }

    public string ChqNo { get; set; }

    public DateTime? ChqDate { get; set; }

    public byte? Posted { get; set; }

    public int? LoginId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public int? AccountId { get; set; }

    public string Description { get; set; }

    public decimal? Debit { get; set; }

    public decimal? Credit { get; set; }

    public short? SeqNo { get; set; }

    public int? DepartmentId { get; set; }

    public int? ItemId { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? CostRate { get; set; }

    public int? InvoiceId { get; set; }

    public int? SoseqNo { get; set; }
}