// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class IssOutMview
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int? PartyId { get; set; }

    public int RefNo { get; set; }

    public string DrefNo { get; set; }

    public int? CompanyId { get; set; }

    public string PartyName { get; set; }

    public decimal Amount { get; set; }

    public int TotalSeqNo { get; set; }

    public string InputType { get; set; }

    public int? ItemId { get; set; }

    public int? BrandId { get; set; }

    public int? QualityId { get; set; }

    public string ItemName { get; set; }

    public string BrandName { get; set; }

    public string QualityName { get; set; }

    public decimal Drate { get; set; }
}