// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class IssueM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int RefNo { get; set; }

    public string DrefNo { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public int? ItemId { get; set; }

    public int? QualityId { get; set; }

    public int? BrandId { get; set; }

    public decimal Dquantity { get; set; }

    public int? ProcessId { get; set; }

    public int? PartyId { get; set; }

    public int? DepartmentId { get; set; }

    public int? ContractId { get; set; }

    public string ProcessRef { get; set; }

    public int? JsizeId { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<IssueD> IssueDs { get; set; } = new List<IssueD>();

    public virtual ICollection<RecFinishD> RecFinishDs { get; set; } = new List<RecFinishD>();

    public virtual ICollection<RecevD> RecevDs { get; set; } = new List<RecevD>();

    public virtual User User { get; set; }
}