// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ItemDetailView
{
    public int Id { get; set; }

    public int? RefId { get; set; }

    public int? ItemId { get; set; }

    public decimal Quantity { get; set; }

    public decimal Quantity2 { get; set; }

    public decimal Quantity3 { get; set; }

    public string ItemName { get; set; }
}