// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ItemCosting
{
    public int Id { get; set; }

    public int? Period { get; set; }

    public int? DivisionId { get; set; }

    public string InputType { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? CurrentDate { get; set; }

    public DateTime? RefDate { get; set; }

    public string RefId { get; set; }

    public short? SeqNo { get; set; }

    public string ItemId { get; set; }

    public decimal? Pqnty { get; set; }

    public decimal? Prate { get; set; }

    public decimal? Pamount { get; set; }

    public decimal? Sqnty { get; set; }

    public decimal? Samount { get; set; }

    public decimal? BalQnty { get; set; }

    public decimal? Srate { get; set; }

    public decimal? BalAmount { get; set; }
}