// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Item
{
    public int Id { get; set; }

    public bool? Status { get; set; }

    public string Name { get; set; }

    public string Hscode { get; set; }

    public string Description { get; set; }

    public int? CategoryId { get; set; }

    public int? UnitId { get; set; }

    public decimal? Packing { get; set; }
}