// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Accounting.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Accounting.Models
{
    public partial interface IwebappContextProcedures
    {
        Task<List<AccountSummaryResult>> AccountSummaryAsync(int? menuID, string dateFrom1, string dateTo1, string divisionFrom, string accountFrom, string groupFrom, int? cUserID, int? start, int? length, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<CustomerProfileReportResult>> CustomerProfileReportAsync(string dateFrom1, string dateTo1, string sPersonFrom, string sPersonTo, string accountFrom, string accountTo, int? start, int? length, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetUserWiseAccountResult>> GetUserWiseAccountAsync(int? cUserID, int? natureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
