// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class JobDepartment
{
    public int RefId { get; set; }

    public int? DepartmentId { get; set; }

    public int ItemId { get; set; }

    public int SizeId { get; set; }

    public decimal? Quantity { get; set; }
}