// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class JobOrderDatum
{
    public int JobId { get; set; }

    public string JobName { get; set; }

    public int? ItemId { get; set; }

    public string ItemName { get; set; }

    public int? BrandId { get; set; }

    public string BrandName { get; set; }

    public int? QualityId { get; set; }

    public string QualityName { get; set; }

    public decimal Dquantity { get; set; }
}