// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class JorderD
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int ItemId { get; set; }

    public decimal Quantity { get; set; }

    public decimal Rate { get; set; }

    public decimal? Amount { get; set; }

    public string Remarks { get; set; }

    public int? LocationId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? DepartmentId { get; set; }

    public int? SizeId { get; set; }

    public virtual Item Item { get; set; }

    public virtual JorderM Ref { get; set; }
}