// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class JorderD2
{
    public int Id { get; set; }

    public int? RefId { get; set; }

    public int? DepartmentId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int RefSeq { get; set; }

    public virtual JorderM Ref { get; set; }
}