// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Ledger
{
    public long LedgerId { get; set; }

    public int CompanyId { get; set; }

    public int AccountId { get; set; }

    public DateOnly Date { get; set; }

    public string VoucherNo { get; set; }

    public string Narration { get; set; }

    public decimal Debit { get; set; }

    public decimal Credit { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}