// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class LoanRecView
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int BookCode { get; set; }

    public string VoucherNo { get; set; }

    public int Mcode { get; set; }

    public string Voucher { get; set; }

    public int CompanyId { get; set; }

    public string Book { get; set; }

    public decimal Amount { get; set; }

    public int TotalSeqNo { get; set; }

    public string InputType { get; set; }

    public string Cheque { get; set; }

    public DateOnly? ChkDate { get; set; }

    public string AccountName { get; set; }

    public string Descriptions { get; set; }

    public string DateTitle { get; set; }

    public string ChequeDateT { get; set; }

    public string Dtitle { get; set; }

    public string Po { get; set; }

    public int? ActCode { get; set; }

    public string InvoiceAmtT { get; set; }

    public decimal? InvoiceAmt { get; set; }

    public string ChequeT { get; set; }

    public string Ivoucher { get; set; }
}