// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class LoanRecDview
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public decimal Amount { get; set; }

    public DateOnly? ChkDate { get; set; }

    public string Remarks { get; set; }

    public string Cheque { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? BookCode { get; set; }

    public int? IrefId { get; set; }

    public string BookName { get; set; }

    public decimal? InvoiceAmt { get; set; }

    public decimal BalanceAmt { get; set; }

    public string Ivoucher { get; set; }

    public DateOnly? Idate { get; set; }
}