// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Location
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public int? ActId { get; set; }

    public virtual ICollection<CostSheetD> CostSheetDs { get; set; } = new List<CostSheetD>();

    public virtual ICollection<DchallanD> DchallanDs { get; set; } = new List<DchallanD>();

    public virtual ICollection<FocinvoiceD> FocinvoiceDs { get; set; } = new List<FocinvoiceD>();

    public virtual ICollection<InvAdjustD> InvAdjustDs { get; set; } = new List<InvAdjustD>();

    public virtual ICollection<IopeningD> IopeningDs { get; set; } = new List<IopeningD>();

    public virtual ICollection<IssOutD> IssOutDs { get; set; } = new List<IssOutD>();

    public virtual ICollection<IssueD> IssueDs { get; set; } = new List<IssueD>();

    public virtual ICollection<PinvoiceD> PinvoiceDs { get; set; } = new List<PinvoiceD>();

    public virtual ICollection<PreturnD> PreturnDs { get; set; } = new List<PreturnD>();

    public virtual ICollection<RchallanD> RchallanDs { get; set; } = new List<RchallanD>();

    public virtual ICollection<RecFinishD> RecFinishDs { get; set; } = new List<RecFinishD>();

    public virtual ICollection<RecOutD> RecOutDs { get; set; } = new List<RecOutD>();

    public virtual ICollection<RecevD> RecevDs { get; set; } = new List<RecevD>();

    public virtual ICollection<SinvoiceD> SinvoiceDs { get; set; } = new List<SinvoiceD>();

    public virtual ICollection<SreturnD> SreturnDs { get; set; } = new List<SreturnD>();

    public virtual ICollection<StaxInvD> StaxInvDs { get; set; } = new List<StaxInvD>();
}