// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class MailSetting
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public int? Ports { get; set; }

    public string Smtp { get; set; }
}