// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Menu
{
    public int MenuId { get; set; }

    public int? ModuleId { get; set; }

    public string MenuName { get; set; }

    public string MenuLink { get; set; }

    public string MenuDescription { get; set; }

    public int? MenuType { get; set; }

    public int? Position { get; set; }

    public int? ParentId { get; set; }

    public string IconPath { get; set; }

    public bool? Avaialble { get; set; }

    public string ReportName { get; set; }

    public string ReportProcedure { get; set; }

    public string Fview { get; set; }

    public string Fcontroller { get; set; }

    public int? Fparameter { get; set; }

    public string FinputType { get; set; }

    public int? MenuStatus { get; set; }

    public virtual Module Module { get; set; }

    public virtual ICollection<RightsOnRole> RightsOnRoles { get; set; } = new List<RightsOnRole>();
}