// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Menu
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Moduleid { get; set; }

    public string Controller { get; set; }

    public string Action { get; set; }

    public byte? Sort { get; set; }

    public string Subnameclass { get; set; }

    public string Namelink { get; set; }

    public string Target { get; set; }

    public string Nameclass { get; set; }

    public int? Menuid { get; set; }

    public string Apiaction { get; set; }

    public int IsApi { get; set; }

    public string CreateMessage { get; set; }

    public string UpdateMessage { get; set; }

    public string RemoveMessage { get; set; }

    public string Apicontroller { get; set; }

    public virtual Module Module { get; set; }
}