// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Module
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public string Icon { get; set; }

    public byte? Seqno { get; set; }

    public string Subname { get; set; }

    public string Nameclass { get; set; }

    public int? ParentId { get; set; }

    public virtual ICollection<Menu> Menus { get; set; } = new List<Menu>();
}