// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Module
{
    public int ModuleId { get; set; }

    public string ModuleDescription { get; set; }

    public string ModuleLink { get; set; }

    public int? PositionId { get; set; }

    public bool? Available { get; set; }

    public virtual ICollection<Menu> Menus { get; set; } = new List<Menu>();

    public virtual ICollection<RightsOnRole> RightsOnRoles { get; set; } = new List<RightsOnRole>();
}