// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class OwnerEquity
{
    public int Id { get; set; }

    public int? CompanyId { get; set; }

    public int? CapitalId { get; set; }

    public int? InvestmentId { get; set; }

    public int? DrawingId { get; set; }

    public int? Perc { get; set; }

    public virtual Chart Capital { get; set; }

    public virtual Company Company { get; set; }

    public virtual Chart Drawing { get; set; }

    public virtual Chart Investment { get; set; }
}