// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PayClassM
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public int? Adid1 { get; set; }

    public int? Adid2 { get; set; }

    public int? Adid3 { get; set; }

    public int? Adid4 { get; set; }

    public int? Adid5 { get; set; }

    public int? Adid6 { get; set; }

    public int? Adid7 { get; set; }

    public int? Adid8 { get; set; }

    public int? Ddid1 { get; set; }

    public int? Ddid2 { get; set; }

    public int? Ddid3 { get; set; }

    public int? Ddid4 { get; set; }

    public int? Ddid5 { get; set; }

    public int? Ddid6 { get; set; }

    public int? CompanyId { get; set; }

    public int? Adid9 { get; set; }

    public int? Adid10 { get; set; }

    public int? Ddid7 { get; set; }

    public int? Ddid8 { get; set; }

    public int? Ddid9 { get; set; }

    public int? Ddid10 { get; set; }

    public int? Ddid11 { get; set; }

    public int? Ddid12 { get; set; }

    public virtual Company Company { get; set; }
}