// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PayDepartment
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public string TimeIn { get; set; }

    public string TimeOut { get; set; }

    public string GraceTime { get; set; }

    public string HalfTime { get; set; }
}