// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PayEmployeLoanM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int Mcode { get; set; }

    public string Voucher { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public int? ActCode { get; set; }

    public decimal Amount { get; set; }

    public int? ItemId { get; set; }

    public int? DepartmentId { get; set; }

    public decimal? IntAmount { get; set; }

    public DateOnly? WarDate { get; set; }

    public bool IsActive { get; set; }

    public int? IrefId { get; set; }

    public int? Imcode { get; set; }

    public decimal Pamount { get; set; }

    public bool IsLock { get; set; }

    public virtual Chart ActCodeNavigation { get; set; }

    public virtual Company Company { get; set; }

    public virtual User User { get; set; }
}