// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PayEmployeeM
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string FatherName { get; set; }

    public int? DepartmentId { get; set; }

    public int? PositionId { get; set; }

    public int? ClassId { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public decimal? Adamount1 { get; set; }

    public decimal? Adamount2 { get; set; }

    public decimal? Adamount3 { get; set; }

    public decimal? Adamount4 { get; set; }

    public decimal? Adamount5 { get; set; }

    public decimal? Adamount6 { get; set; }

    public decimal? Adamount7 { get; set; }

    public decimal? Adamount8 { get; set; }

    public decimal? Ddamount1 { get; set; }

    public decimal? Ddamount2 { get; set; }

    public decimal? Ddamount3 { get; set; }

    public decimal? Ddamount4 { get; set; }

    public decimal? Ddamount5 { get; set; }

    public decimal? Ddamount6 { get; set; }

    public decimal? Llqty1 { get; set; }

    public decimal? Llqty2 { get; set; }

    public decimal? Llqty3 { get; set; }

    public string Address { get; set; }

    public string Contact { get; set; }

    public string Cnic { get; set; }

    public string Ntn { get; set; }

    public DateOnly? Ddate { get; set; }

    public decimal? Age { get; set; }

    public int? GenderId { get; set; }

    public int? PayTypeId { get; set; }

    public string AccountNo { get; set; }

    public string Bdescription { get; set; }

    public DateOnly? Jdate { get; set; }

    public DateOnly? Tdate { get; set; }

    public string Eobi { get; set; }

    public string Sac { get; set; }

    public string ServiceP { get; set; }

    public string Grade { get; set; }

    public decimal? OverTime { get; set; }

    public string Eduction { get; set; }

    public decimal? Othour { get; set; }

    public int? EnRollId { get; set; }

    public bool IsAdmin { get; set; }

    public string MachineSerial { get; set; }

    public decimal? Adamount9 { get; set; }

    public decimal? Adamount10 { get; set; }

    public decimal? Ddamount7 { get; set; }

    public decimal? Ddamount8 { get; set; }

    public decimal? Ddamount9 { get; set; }

    public decimal? Ddamount10 { get; set; }

    public decimal? Ddamount11 { get; set; }

    public decimal? Ddamount12 { get; set; }

    public DateOnly? Bdate { get; set; }

    public string RegNo { get; set; }

    public decimal? Llqty4 { get; set; }

    public int? LevelId { get; set; }

    public virtual ICollection<PayEmployeAdvanceM> PayEmployeAdvanceMs { get; set; } = new List<PayEmployeAdvanceM>();
}