// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PayHolidayDetail
{
    public int Id { get; set; }

    public int? RefId { get; set; }

    public DateTime? HolidayDate { get; set; }

    public virtual PayPublicM Ref { get; set; }
}