// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PayManualAtt
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int Mcode { get; set; }

    public string Voucher { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public int? ActCode { get; set; }

    public string TimeIn { get; set; }

    public string TimeOut { get; set; }

    public bool IsActive { get; set; }

    public bool ChkTimeOut { get; set; }

    public virtual User User { get; set; }
}