// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PayPublicM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int Mcode { get; set; }

    public string Voucher { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public int? ActCode { get; set; }

    public decimal Amount { get; set; }

    public int? ItemId { get; set; }

    public int? DepartmentId { get; set; }

    public DateOnly? WarDate { get; set; }

    public DateOnly? Tdate { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<PayHolidayDetail> PayHolidayDetails { get; set; } = new List<PayHolidayDetail>();

    public virtual User User { get; set; }
}