// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PaySalaryM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int? DepartmentId { get; set; }

    public int RefNo { get; set; }

    public string DrefNo { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public DateOnly? WarDate { get; set; }

    public virtual ICollection<PaySalaryD> PaySalaryDs { get; set; } = new List<PaySalaryD>();

    public virtual User User { get; set; }
}