// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PaySalaryDview
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int? AccountId { get; set; }

    public string Cheque { get; set; }

    public decimal? Adays { get; set; }

    public decimal? Othours { get; set; }

    public int? A01account { get; set; }

    public int? A02account { get; set; }

    public int? A03account { get; set; }

    public int? A04account { get; set; }

    public int? A05account { get; set; }

    public int? A06account { get; set; }

    public int? A07account { get; set; }

    public int? TotalDays { get; set; }

    public decimal? Salary { get; set; }

    public decimal? Adamount1 { get; set; }

    public decimal? Adamount2 { get; set; }

    public decimal? Adamount3 { get; set; }

    public decimal? Adamount4 { get; set; }

    public decimal? Adamount5 { get; set; }

    public decimal? Adamount6 { get; set; }

    public decimal? Adamount7 { get; set; }

    public decimal? Adamount8 { get; set; }

    public int? AdvanceAccount { get; set; }

    public int? LoanAccount { get; set; }

    public int? D01account { get; set; }

    public int? D02account { get; set; }

    public int? D03account { get; set; }

    public int? D04account { get; set; }

    public decimal? SalaryPayable { get; set; }

    public decimal? Ddamount1 { get; set; }

    public decimal? Ddamount2 { get; set; }

    public decimal? Ddamount3 { get; set; }

    public decimal? Ddamount4 { get; set; }

    public decimal? Loan { get; set; }

    public decimal? Advance { get; set; }

    public decimal? SalaryPaid { get; set; }

    public decimal? Allowances { get; set; }

    public decimal? Deductions { get; set; }

    public decimal? NetAmount { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? LoanId { get; set; }

    public int? AdvanceId { get; set; }

    public int? PayTypeId { get; set; }

    public int? PayAccountId { get; set; }

    public int? CompanyId { get; set; }

    public int? A09account { get; set; }

    public int? A010account { get; set; }

    public decimal? Adamount9 { get; set; }

    public decimal? Adamount10 { get; set; }

    public int? D07account { get; set; }

    public int? D08account { get; set; }

    public int? D09account { get; set; }

    public int? D010account { get; set; }

    public int? D011account { get; set; }

    public int? D012account { get; set; }

    public decimal? Ddamount7 { get; set; }

    public decimal? Ddamount8 { get; set; }

    public decimal? Ddamount9 { get; set; }

    public decimal? Ddamount10 { get; set; }

    public decimal? Ddamount11 { get; set; }

    public decimal? Ddamount12 { get; set; }

    public string EmployeName { get; set; }
}