// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Person1
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public int Addresses { get; set; }
}