// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PinvoiceM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int? PartyId { get; set; }

    public int RefNo { get; set; }

    public string DrefNo { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public int? RefId { get; set; }

    public string PrefNo { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Mwhtax { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual Company Company { get; set; }

    public virtual Chart Party { get; set; }

    public virtual ICollection<PaymentD2> PaymentD2s { get; set; } = new List<PaymentD2>();

    public virtual ICollection<PinvoiceD> PinvoiceDs { get; set; } = new List<PinvoiceD>();

    public virtual User User { get; set; }
}