// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PpinvoiceD
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int ItemId { get; set; }

    public decimal Quantity { get; set; }

    public decimal Rate { get; set; }

    public decimal? Amount { get; set; }

    public string Remarks { get; set; }

    public int LocationId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? BrandId { get; set; }

    public int? QualityId { get; set; }

    public int? SizeId { get; set; }

    public decimal Packing { get; set; }

    public decimal Pcs { get; set; }

    public string Unit { get; set; }

    public decimal? GstPerc { get; set; }

    public decimal? ComPerc { get; set; }

    public decimal? CommAmt { get; set; }

    public decimal? NetAmount { get; set; }

    public virtual PpinvoiceM Ref { get; set; }
}