// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ProcessD2
{
    public int Id { get; set; }

    public int? RefId { get; set; }

    public int RefNo { get; set; }

    public string DrefNo { get; set; }

    public int? CompanyId { get; set; }

    public int? DepartmentId { get; set; }

    public int? PartyId { get; set; }

    public decimal Quantity { get; set; }

    public decimal Rate { get; set; }

    public decimal? Amount { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? Imcode { get; set; }

    public virtual ICollection<ProcessD4> ProcessD4s { get; set; } = new List<ProcessD4>();

    public virtual ProcessM Ref { get; set; }
}