// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ProcessD
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int? JobId { get; set; }

    public decimal? Cquantity { get; set; }

    public int Ctid { get; set; }

    public int? DepartmentId { get; set; }

    public decimal? Oquantity { get; set; }

    public int ItemId { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? Aperc { get; set; }

    public decimal? Aquantity { get; set; }

    public decimal? Tquantity { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? SizeId { get; set; }

    public virtual Item Item { get; set; }

    public virtual ProcessM Ref { get; set; }
}