// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ProcessM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int RefNo { get; set; }

    public string DrefNo { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public int? ItemId { get; set; }

    public int? QualityId { get; set; }

    public int? BrandId { get; set; }

    public string Border { get; set; }

    public decimal Dquantity { get; set; }

    public int? JobId { get; set; }

    public int? PartyId { get; set; }

    public decimal Aperc { get; set; }

    public virtual Company Company { get; set; }

    public virtual JorderM Job { get; set; }

    public virtual ICollection<ProcessD2> ProcessD2s { get; set; } = new List<ProcessD2>();

    public virtual ICollection<ProcessD> ProcessDs { get; set; } = new List<ProcessD>();

    public virtual User User { get; set; }
}