// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ProcessD4
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int? JobId { get; set; }

    public int? SizeId { get; set; }

    public decimal Quantity { get; set; }

    public int? UserId { get; set; }

    public virtual ProcessD2 Ref { get; set; }
}