// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class PublishedDesign
{
    public int Id { get; set; }

    public string ElementsJson { get; set; }

    public DateTime PublishedOn { get; set; }
}