// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class RecevD2
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int? IrefSeq { get; set; }

    public string DrefNo { get; set; }

    public int? CompanyId { get; set; }

    public string IinputType { get; set; }

    public int? ContractId { get; set; }

    public int? FsizeId { get; set; }

    public int ItemId { get; set; }

    public int? BrandId { get; set; }

    public int? QualityId { get; set; }

    public int? SizeId { get; set; }

    public decimal Quantity { get; set; }

    public decimal Rate { get; set; }

    public decimal? CostRate { get; set; }

    public decimal? Amount { get; set; }

    public string RefType { get; set; }

    public int LocationId { get; set; }

    public DateTime? CreateDate { get; set; }

    public decimal? Consume { get; set; }

    public int? ProcessId { get; set; }

    public int? AccountId { get; set; }

    public int? AccountId2 { get; set; }

    public int? JobId { get; set; }

    public decimal? IcostRate { get; set; }

    public virtual RecevD IrefSeqNavigation { get; set; }
}