// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class RecevD3
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int? RefSeq { get; set; }

    public int? CompanyId { get; set; }

    public int? RefContractId { get; set; }

    public int? RefSizeId { get; set; }

    public decimal? RefQnty { get; set; }

    public string IrefType { get; set; }

    public int? IrefId { get; set; }

    public int? IrefSeqNo { get; set; }

    public decimal Quantity { get; set; }

    public decimal? CostRate { get; set; }

    public decimal? Amount { get; set; }

    public DateTime? CreateDate { get; set; }

    public virtual RecevD RefSeqNavigation { get; set; }
}