// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class RecevD
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int ItemId { get; set; }

    public decimal Quantity { get; set; }

    public decimal? Rate { get; set; }

    public decimal? Amount { get; set; }

    public string Remarks { get; set; }

    public int LocationId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? IrefId { get; set; }

    public int? BrandId { get; set; }

    public int? QualityId { get; set; }

    public int? SizeId { get; set; }

    public int? JobId { get; set; }

    public decimal? IcostRate { get; set; }

    public decimal? LcostRate { get; set; }

    public decimal? CostRate { get; set; }

    public virtual IssueM Iref { get; set; }

    public virtual Item Item { get; set; }

    public virtual Location Location { get; set; }

    public virtual ICollection<RecevD2> RecevD2s { get; set; } = new List<RecevD2>();

    public virtual ICollection<RecevD3> RecevD3s { get; set; } = new List<RecevD3>();

    public virtual RecevM Ref { get; set; }
}