// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class RecFinishD
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public int ItemId { get; set; }

    public decimal Quantity { get; set; }

    public decimal? Rate { get; set; }

    public decimal? Amount { get; set; }

    public string Remarks { get; set; }

    public int LocationId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UserId { get; set; }

    public int? IrefId { get; set; }

    public int? BrandId { get; set; }

    public int? QualityId { get; set; }

    public int? SizeId { get; set; }

    public int? JobId { get; set; }

    public decimal? IcostRate { get; set; }

    public decimal? LcostRate { get; set; }

    public decimal? McostRate { get; set; }

    public decimal? RejectQty { get; set; }

    public virtual IssueM Iref { get; set; }

    public virtual Item Item { get; set; }

    public virtual Location Location { get; set; }

    public virtual ICollection<RecFinishD2> RecFinishD2s { get; set; } = new List<RecFinishD2>();

    public virtual ICollection<RecFinishD3> RecFinishD3s { get; set; } = new List<RecFinishD3>();

    public virtual RecFinishM Ref { get; set; }
}