// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class RecFinishM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int? PartyId { get; set; }

    public int RefNo { get; set; }

    public string DrefNo { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public int? RefId { get; set; }

    public int? TrefId { get; set; }

    public int? SizeId { get; set; }

    public int? CRefId { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<RecFinishD> RecFinishDs { get; set; } = new List<RecFinishD>();

    public virtual User User { get; set; }
}