// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ReportMaster
{
    public int Id { get; set; }

    public int? MenuId { get; set; }

    public int? FilterId { get; set; }
}