// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Report
{
    public int Id { get; set; }

    public string ReportKey { get; set; }

    public string StoredProcedure { get; set; }

    public string Description { get; set; }
}