// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ReportFilterGroupField
{
    public int Id { get; set; }

    public string ReportKey { get; set; }

    public string FieldName { get; set; }

    public string DisplayName { get; set; }

    public string FieldType { get; set; }

    public bool IsFilterAllowed { get; set; }

    public bool IsGroupAllowed { get; set; }

    public string DataSourceUrl { get; set; }

    public int SortOrder { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}