// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class RightsOnRole
{
    public int RightsId { get; set; }

    public int? RoleId { get; set; }

    public int? ModuleId { get; set; }

    public int? MenuId { get; set; }

    public bool? Insert { get; set; }

    public bool? Remove { get; set; }

    public bool? Update { get; set; }

    public bool? View { get; set; }

    public virtual Menu Menu { get; set; }

    public virtual Module Module { get; set; }

    public virtual Role Role { get; set; }
}