// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Role
{
    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public string RoleDesc { get; set; }

    public virtual ICollection<RightsOnRole> RightsOnRoles { get; set; } = new List<RightsOnRole>();

    public virtual ICollection<UsersDetail> UsersDetails { get; set; } = new List<UsersDetail>();
}