// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class RpttrialBalance
{
    public int Id { get; set; }

    public string AccountName { get; set; }

    public double? Debit { get; set; }

    public double? Credit { get; set; }

    public string GroupName { get; set; }

    public int? Type { get; set; }

    public int? AccountId { get; set; }

    public double? AdjWt { get; set; }

    public string ChqNo { get; set; }

    public double? AvgWt { get; set; }

    public int? DivisionId { get; set; }

    public DateOnly? ChqDate { get; set; }

    public string ChqStatus { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string Description { get; set; }

    public string Description2 { get; set; }

    public string DispDivisionName { get; set; }

    public int? FlockId { get; set; }

    public string FlockName { get; set; }

    public double? GrossWt { get; set; }

    public int? GroupId { get; set; }

    public string InputType { get; set; }

    public string ItemName { get; set; }

    public double? Less { get; set; }

    public double? NetWt { get; set; }

    public double? OppBalance { get; set; }

    public string OppName { get; set; }

    public double? Pcs { get; set; }

    public int? Period { get; set; }

    public double? Quantity { get; set; }

    public double? Rate { get; set; }

    public string ReferenceNo { get; set; }

    public int? SeqNo { get; set; }

    public string VehicleNo { get; set; }

    public string VoucherNo { get; set; }

    public DateOnly? Date { get; set; }
}