// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class SaleInvoiceMasterView
{
    public bool? Status { get; set; }

    public int Id { get; set; }

    public string RefernceNo { get; set; }

    public string Fbrinvoice { get; set; }

    public byte[] Fbrqrcode { get; set; }

    public string Customer { get; set; }

    public string Company { get; set; }

    public string UserName { get; set; }

    public decimal? TotalAmount { get; set; }

    public DateOnly? Mdate { get; set; }
}