// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class SaleEntryDetail
{
    public int? Code { get; set; }

    public string InputType { get; set; }

    public int? DivisionId { get; set; }

    public int? RefNo { get; set; }

    public DateTime? Date { get; set; }

    public int? ChqNo { get; set; }

    public int? ChqDate { get; set; }

    public int Posted { get; set; }

    public int? UserId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public int? AccountId { get; set; }

    public string Description { get; set; }

    public decimal? Debit { get; set; }

    public int Credit { get; set; }

    public int SeqNo { get; set; }

    public int? DepartmentId { get; set; }

    public int? ItemId { get; set; }

    public int? Quantity { get; set; }

    public int? CostRate { get; set; }

    public int InvoiceId { get; set; }

    public int SoseqNo { get; set; }
}