// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class SaleInvoiceDetailView
{
    public int Id { get; set; }

    public int? Refid { get; set; }

    public int? UserId { get; set; }

    public DateTime? Date { get; set; }

    public int? ItemId { get; set; }

    public decimal? Package { get; set; }

    public decimal? Packing { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? Rate { get; set; }

    public decimal? Amount { get; set; }

    public decimal? Tax { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? NetAmount { get; set; }

    public string ItemName { get; set; }
}