// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class SaleCostRef
{
    public int Id { get; set; }

    public int? Period { get; set; }

    public int? DivisionId { get; set; }

    public int? SaleRefId { get; set; }

    public short? SaleSeqNo { get; set; }

    public string SaleInputType { get; set; }

    public int? ItemId { get; set; }

    public decimal? Quantity { get; set; }

    public string InputType { get; set; }

    public int? RefId { get; set; }

    public short? SeqNo { get; set; }

    public decimal? CostRate { get; set; }

    public decimal? CostAmount { get; set; }
}