// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class SaleInvoiceMaster
{
    public int Id { get; set; }

    public bool? Status { get; set; }

    public int? UserId { get; set; }

    public DateTime? Date { get; set; }

    public int? CustomerId { get; set; }

    public string Description { get; set; }

    public string Fbrinvoice { get; set; }

    public byte[] Fbrqrcode { get; set; }

    public string RefernceNo { get; set; }

    public virtual ICollection<SaleInvoiceDetail> SaleInvoiceDetails { get; set; } = new List<SaleInvoiceDetail>();
}