// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class SbookView
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int? BookCode { get; set; }

    public string VoucherNo { get; set; }

    public int Mcode { get; set; }

    public string Voucher { get; set; }

    public int CompanyId { get; set; }

    public string Book { get; set; }

    public decimal Amount { get; set; }

    public int TotalSeqNo { get; set; }

    public string InputType { get; set; }

    public int? BookId { get; set; }

    public string ChqNo { get; set; }

    public DateTime? ChqDate { get; set; }

    public string BookName { get; set; }

    public string Slip { get; set; }

    public int? TypeId { get; set; }

    public string TypeName { get; set; }

    public decimal Amount2 { get; set; }

    public string UserName { get; set; }

    public int? LocationId { get; set; }
}