// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class SbookM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public string VoucherNo { get; set; }

    public int Mcode { get; set; }

    public string Voucher { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public int? ActCode { get; set; }

    public decimal Amount { get; set; }

    public decimal Gamount { get; set; }

    public decimal Wamount { get; set; }

    public decimal Whperc { get; set; }

    public int? BookId { get; set; }

    public string ChqNo { get; set; }

    public DateTime? ChqDate { get; set; }

    public string SlipNo { get; set; }

    public int? TypeId { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual Chart ActCodeNavigation { get; set; }

    public virtual Company Company { get; set; }

    public virtual User User { get; set; }
}