// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Setting
{
    public int Code { get; set; }

    public string Value { get; set; }

    public string Prefix { get; set; }

    public string Remarks { get; set; }
}