// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class Setting
{
    public int Id { get; set; }

    public string SettingName { get; set; }

    public string SettingValue { get; set; }

    public DateTime? CreatedAt { get; set; }
}