// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class SinvoiceMview
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int? PartyId { get; set; }

    public int RefNo { get; set; }

    public string DrefNo { get; set; }

    public int? CompanyId { get; set; }

    public string PartyName { get; set; }

    public decimal Amount { get; set; }

    public string AmountCompact { get; set; }

    public int? TotalSeqNo { get; set; }

    public string InputType { get; set; }

    public string CDate { get; set; }

    public decimal? AdvanceBal { get; set; }

    public string AdvanceBalCompact { get; set; }

    public decimal? Quantity { get; set; }

    public decimal PaidAmount { get; set; }

    public decimal? NetBalance { get; set; }

    public string UserName { get; set; }

    public int? LocationId { get; set; }
}