// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting.Models
{
    public partial class sp_LedgerReportResult
    {
        public DateOnly Date { get; set; }
        [StringLength(50)]
        public string VoucherNo { get; set; }
        [StringLength(500)]
        public string Narration { get; set; }
        [Column("Debit", TypeName = "decimal(18,2)")]
        public decimal Debit { get; set; }
        [Column("Credit", TypeName = "decimal(18,2)")]
        public decimal Credit { get; set; }
        [Column("RunningBalance", TypeName = "decimal(38,2)")]
        public decimal? RunningBalance { get; set; }
    }
}
