// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class StaxInvM
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string Remarks { get; set; }

    public int? PartyId { get; set; }

    public int RefNo { get; set; }

    public string DrefNo { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CurrentDate { get; set; }

    public string InputType { get; set; }

    public int? UserId { get; set; }

    public int? RefId { get; set; }

    public decimal? Freight { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Mwhtax { get; set; }

    public int SpersonId { get; set; }

    public decimal? AdvanceBal { get; set; }

    public decimal? AdvancePaid { get; set; }

    public int RcptAccount { get; set; }

    public decimal RcptAmount { get; set; }

    public int RcptAccount2 { get; set; }

    public decimal RcptAmount2 { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<StaxInvD2> StaxInvD2s { get; set; } = new List<StaxInvD2>();

    public virtual ICollection<StaxInvD> StaxInvDs { get; set; } = new List<StaxInvD>();

    public virtual User User { get; set; }
}