// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class StockReference
{
    public int Id { get; set; }

    public string RefType { get; set; }

    public string DrefType { get; set; }

    public string Title1 { get; set; }

    public string Title2 { get; set; }

    public string Title3 { get; set; }

    public byte? SeqNo { get; set; }
}