// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class StockCostingCustom
{
    public int Id { get; set; }

    public int? RefCompanyId { get; set; }

    public int? RefItemId { get; set; }

    public int? RefLocationId { get; set; }

    public string RefType { get; set; }

    public int? RefId { get; set; }

    public int? RefSeqNo { get; set; }

    public decimal? RefQnty { get; set; }

    public decimal? RefRate { get; set; }

    public string IrefType { get; set; }

    public int? IrefId { get; set; }

    public int? IrefSeqNo { get; set; }

    public decimal? Qnty { get; set; }

    public decimal? Nqnty { get; set; }

    public decimal? CostRate { get; set; }

    public byte? IsAdd { get; set; }

    public DateTime? CurrentDateTime { get; set; }

    public decimal? CostAmount { get; set; }

    public int? RefJobId { get; set; }

    public int? RefContractId { get; set; }

    public int? RefProcessId { get; set; }

    public int? RefContractSizeId { get; set; }

    public int? AccountId { get; set; }

    public int? AccountId2 { get; set; }

    public byte? IsWip { get; set; }
}