// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class TrialBalance
{
    public int Id { get; set; }

    public string AccountName { get; set; }

    public int? GroupId { get; set; }

    public decimal? Debit { get; set; }

    public decimal? Credit { get; set; }

    public string Code { get; set; }

    public string VoucherNo { get; set; }

    public string ChqNo { get; set; }

    public DateOnly? Date { get; set; }

    public DateOnly? ChqDate { get; set; }

    public string ChqStatus { get; set; }

    public int? AccountId { get; set; }

    public string Description { get; set; }

    public short? SeqNo { get; set; }

    public string InputType { get; set; }

    public string OppName { get; set; }

    public int? DivisionId { get; set; }

    public string Division { get; set; }

    public int? DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public string Description2 { get; set; }

    public int? FlockId { get; set; }

    public string FlockName { get; set; }

    public string VehicleNo { get; set; }

    public string ItemName { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? Pcs { get; set; }

    public decimal? Less { get; set; }

    public decimal? AvgWt { get; set; }

    public decimal? GrossWt { get; set; }

    public decimal? AdjWt { get; set; }

    public decimal? NetWt { get; set; }

    public decimal? Rate { get; set; }

    public DateTime? CurrentDate { get; set; }
}