// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class UserReportView
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string ReportKey { get; set; }

    public string ViewName { get; set; }

    public string Filters { get; set; }

    public string GroupBy { get; set; }

    public bool IsFavorite { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}