// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class UserPooling
{
    public int Id { get; set; }

    public int? EnRollId { get; set; }

    public string Name { get; set; }

    public int? MachineNo { get; set; }

    public string MachineSerial { get; set; }
}