// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class UsersHi
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string Form { get; set; }

    public string Action { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? Time { get; set; }

    public string ReferenceNo { get; set; }

    public string Amount { get; set; }

    public string ComputerName { get; set; }

    public int? CompanyId { get; set; }

    public string Describe { get; set; }

    public int? RefId { get; set; }

    public string InputType { get; set; }
}