// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class ViewMonthlyExpense
{
    public int MonthNumber { get; set; }

    public string MonthName { get; set; }

    public int TotalExpense { get; set; }

    public int SalesYear { get; set; }
}