// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Models;

public partial class VwTotalRevenue
{
    public int Year { get; set; }

    public string MonthName { get; set; }

    public int? Amount { get; set; }

    public int? MonthOrder { get; set; }
}