// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Accounting.Models;

namespace Accounting.Models
{
    public partial class webappContext
    {

        [DbFunction("getdumpdata", "dbo")]
        public static string getdumpdata(string svalue)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("setdumpdata", "dbo")]
        public static string setdumpdata(string svalue)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
