// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Accounting.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Accounting.Models
{
    public partial class webappContext
    {
        private IwebappContextProcedures _procedures;

        public virtual IwebappContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new webappContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IwebappContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class webappContextProcedures : IwebappContextProcedures
    {
        private readonly webappContext _context;

        public webappContextProcedures(webappContext context)
        {
            _context = context;
        }

        public virtual async Task<List<AccountSummaryResult>> AccountSummaryAsync(int? menuID, string dateFrom1, string dateTo1, string divisionFrom, string accountFrom, string groupFrom, int? cUserID, int? start, int? length, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MenuID",
                    Value = menuID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DateFrom1",
                    Size = 10,
                    Value = dateFrom1 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DateTo1",
                    Size = 10,
                    Value = dateTo1 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DivisionFrom",
                    Size = -1,
                    Value = divisionFrom ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AccountFrom",
                    Size = -1,
                    Value = accountFrom ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "GroupFrom",
                    Size = -1,
                    Value = groupFrom ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "cUserID",
                    Value = cUserID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Start",
                    Value = start ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Length",
                    Value = length ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<AccountSummaryResult>("EXEC @returnValue = [dbo].[AccountSummary] @MenuID = @MenuID, @DateFrom1 = @DateFrom1, @DateTo1 = @DateTo1, @DivisionFrom = @DivisionFrom, @AccountFrom = @AccountFrom, @GroupFrom = @GroupFrom, @cUserID = @cUserID, @Start = @Start, @Length = @Length", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<CustomerProfileReportResult>> CustomerProfileReportAsync(string dateFrom1, string dateTo1, string sPersonFrom, string sPersonTo, string accountFrom, string accountTo, int? start, int? length, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "DateFrom1",
                    Size = 10,
                    Value = dateFrom1 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DateTo1",
                    Size = 10,
                    Value = dateTo1 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SPersonFrom",
                    Size = -1,
                    Value = sPersonFrom ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SPersonTo",
                    Size = -1,
                    Value = sPersonTo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AccountFrom",
                    Size = -1,
                    Value = accountFrom ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AccountTo",
                    Size = -1,
                    Value = accountTo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Start",
                    Value = start ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Length",
                    Value = length ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<CustomerProfileReportResult>("EXEC @returnValue = [dbo].[CustomerProfileReport] @DateFrom1 = @DateFrom1, @DateTo1 = @DateTo1, @SPersonFrom = @SPersonFrom, @SPersonTo = @SPersonTo, @AccountFrom = @AccountFrom, @AccountTo = @AccountTo, @Start = @Start, @Length = @Length", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<GetUserWiseAccountResult>> GetUserWiseAccountAsync(int? cUserID, int? natureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "cUserID",
                    Value = cUserID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "NatureID",
                    Value = natureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetUserWiseAccountResult>("EXEC @returnValue = [dbo].[GetUserWiseAccount] @cUserID = @cUserID, @NatureID = @NatureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
