// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Accounting.Models;

public partial class webappContext : DbContext
{
    public webappContext(DbContextOptions<webappContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Abc> Abcs { get; set; }

    public virtual DbSet<AccountOnRole> AccountOnRoles { get; set; }

    public virtual DbSet<AccountOpeningD> AccountOpeningDs { get; set; }

    public virtual DbSet<AccountOpeningDview> AccountOpeningDviews { get; set; }

    public virtual DbSet<AccountOpeningM> AccountOpeningMs { get; set; }

    public virtual DbSet<AccountOpeningMview> AccountOpeningMviews { get; set; }

    public virtual DbSet<App> Apps { get; set; }

    public virtual DbSet<BankPaymentD> BankPaymentDs { get; set; }

    public virtual DbSet<BankPaymentDview> BankPaymentDviews { get; set; }

    public virtual DbSet<BankPaymentM> BankPaymentMs { get; set; }

    public virtual DbSet<BankPaymentMview> BankPaymentMviews { get; set; }

    public virtual DbSet<BankPaymentView> BankPaymentViews { get; set; }

    public virtual DbSet<BankReceiptD> BankReceiptDs { get; set; }

    public virtual DbSet<BankReceiptDview> BankReceiptDviews { get; set; }

    public virtual DbSet<BankReceiptM> BankReceiptMs { get; set; }

    public virtual DbSet<BankReceiptView> BankReceiptViews { get; set; }

    public virtual DbSet<CashPaymentD> CashPaymentDs { get; set; }

    public virtual DbSet<CashPaymentDview> CashPaymentDviews { get; set; }

    public virtual DbSet<CashPaymentM> CashPaymentMs { get; set; }

    public virtual DbSet<CashPaymentMview> CashPaymentMviews { get; set; }

    public virtual DbSet<CashReceiptD> CashReceiptDs { get; set; }

    public virtual DbSet<CashReceiptDview> CashReceiptDviews { get; set; }

    public virtual DbSet<CashReceiptM> CashReceiptMs { get; set; }

    public virtual DbSet<CashReceiptMview> CashReceiptMviews { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Chart> Charts { get; set; }

    public virtual DbSet<ChartActType> ChartActTypes { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<CityCountryView> CityCountryViews { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Design> Designs { get; set; }

    public virtual DbSet<DesignComponent> DesignComponents { get; set; }

    public virtual DbSet<Dropdown> Dropdowns { get; set; }

    public virtual DbSet<Dumpdatum> Dumpdata { get; set; }

    public virtual DbSet<FormDatum> FormData { get; set; }

    public virtual DbSet<FormDefinition> FormDefinitions { get; set; }

    public virtual DbSet<FormField> FormFields { get; set; }

    public virtual DbSet<Gjouranlview> Gjouranlviews { get; set; }

    public virtual DbSet<GjournalD> GjournalDs { get; set; }

    public virtual DbSet<GjournalM> GjournalMs { get; set; }

    public virtual DbSet<IbbookEntry> IbbookEntries { get; set; }

    public virtual DbSet<IcbookEntry> IcbookEntries { get; set; }

    public virtual DbSet<IchequeReqEntry> IchequeReqEntries { get; set; }

    public virtual DbSet<IgmultiEntry> IgmultiEntries { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<Ledger> Ledgers { get; set; }

    public virtual DbSet<MainMenu> MainMenus { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<Module> Modules { get; set; }

    public virtual DbSet<MyDatum> MyData { get; set; }

    public virtual DbSet<Operation> Operations { get; set; }

    public virtual DbSet<PinvoiceD> PinvoiceDs { get; set; }

    public virtual DbSet<PinvoiceM> PinvoiceMs { get; set; }

    public virtual DbSet<PpinvoiceD> PpinvoiceDs { get; set; }

    public virtual DbSet<PpinvoiceM> PpinvoiceMs { get; set; }

    public virtual DbSet<PublishedDesign> PublishedDesigns { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<RpttrialBalance> RpttrialBalances { get; set; }

    public virtual DbSet<SaleInvoiceDetail> SaleInvoiceDetails { get; set; }

    public virtual DbSet<SaleInvoiceDetailView> SaleInvoiceDetailViews { get; set; }

    public virtual DbSet<SaleInvoiceMaster> SaleInvoiceMasters { get; set; }

    public virtual DbSet<SaleInvoiceMasterView> SaleInvoiceMasterViews { get; set; }

    public virtual DbSet<Saleinvoice2> Saleinvoice2s { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<Setting> Settings { get; set; }

    public virtual DbSet<TrialBalance> TrialBalances { get; set; }

    public virtual DbSet<Unit> Units { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserReportView> UserReportViews { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UsersBackup> UsersBackups { get; set; }

    public virtual DbSet<UsersDetail> UsersDetails { get; set; }

    public virtual DbSet<ViewMonthlyExpense> ViewMonthlyExpenses { get; set; }

    public virtual DbSet<ViewMonthlyProfit> ViewMonthlyProfits { get; set; }

    public virtual DbSet<ViewMonthlyRevenue> ViewMonthlyRevenues { get; set; }

    public virtual DbSet<VwTotalRevenue> VwTotalRevenues { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Abc>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ABC__3214EC0745672BB7");

            entity.ToTable("ABC");

            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<AccountOnRole>(entity =>
        {
            entity.HasKey(e => e.RightsId);

            entity.ToTable("AccountOnRole");

            entity.Property(e => e.RightsId).HasColumnName("RightsID");
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.GroupId).HasColumnName("GroupID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Company).WithMany(p => p.AccountOnRoles)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_AccountOnRole_Company");

            entity.HasOne(d => d.User).WithMany(p => p.AccountOnRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_AccountOnRole_User");
        });

        modelBuilder.Entity<AccountOpeningD>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.AccountOpeningD");

            entity.ToTable("AccountOpeningD");

            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ChkDate).HasColumnType("datetime");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AccountOpeningD_CreateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Credit).HasColumnType("money");
            entity.Property(e => e.Debit).HasColumnType("money");
            entity.Property(e => e.PersonId).HasColumnName("PersonID");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Person).WithMany(p => p.AccountOpeningDs)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_AccountOpeningD_AccountOpeningM");
        });

        modelBuilder.Entity<AccountOpeningDview>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("AccountOpeningDView");

            entity.Property(e => e.Accounts)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Credit).HasColumnType("money");
            entity.Property(e => e.Debit).HasColumnType("money");
            entity.Property(e => e.PersonId).HasColumnName("PersonID");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.TotalDebit).HasColumnType("money");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Voucher)
                .HasMaxLength(45)
                .IsUnicode(false);
        });

        modelBuilder.Entity<AccountOpeningM>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.AccountOpeningM");

            entity.ToTable("AccountOpeningM");

            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AccountOpeningM_CurrentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("OP")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AccountOpeningM_InputType");
            entity.Property(e => e.Mcode)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AccountOpeningM_MCode")
                .HasColumnName("MCode");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Vdate)
                .HasColumnType("datetime")
                .HasColumnName("VDate");
            entity.Property(e => e.Voucher)
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasComputedColumnSql("(([InputType]+'-')+right('000000'+CONVERT([varchar](6),[MCode]),(6)))", false);
            entity.Property(e => e.VoucherNo)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Company).WithMany(p => p.AccountOpeningMs)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AccountOpeningM_Company");

            entity.HasOne(d => d.User).WithMany(p => p.AccountOpeningMs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_AccountOpeningM_Users");
        });

        modelBuilder.Entity<AccountOpeningMview>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("AccountOpeningMView");

            entity.Property(e => e.Accounts)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.Book)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.Companyname)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Credit).HasColumnType("money");
            entity.Property(e => e.Debit).HasColumnType("money");
            entity.Property(e => e.InputType)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Mcode).HasColumnName("MCode");
            entity.Property(e => e.Prefix)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Remarks)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Voucher)
                .HasMaxLength(45)
                .IsUnicode(false);
            entity.Property(e => e.VoucherNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<App>(entity =>
        {
            entity.Property(e => e.Color).HasMaxLength(200);
            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__common_ap__Curre__6B99EBCE");
            entity.Property(e => e.Description)
                .HasMaxLength(200)
                .HasColumnName("description");
            entity.Property(e => e.FilePath).HasMaxLength(200);
            entity.Property(e => e.FolderName).HasMaxLength(50);
            entity.Property(e => e.Icon).HasMaxLength(200);
            entity.Property(e => e.IsActive).HasAnnotation("Relational:DefaultConstraintName", "DF_Apps_IsActive");
            entity.Property(e => e.Label)
                .HasMaxLength(200)
                .HasColumnName("label");
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Url).HasMaxLength(200);
        });

        modelBuilder.Entity<BankPaymentD>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.BankPaymentD");

            entity.ToTable("BankPaymentD");

            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.BrecNo1).HasColumnName("BRecNo1");
            entity.Property(e => e.BrecNo2).HasColumnName("BRecNo2");
            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ChkDate).HasColumnType("datetime");
            entity.Property(e => e.CostId).HasColumnName("CostID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BankPaymentD_CreateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.ManualNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PersonId).HasColumnName("PersonID");
            entity.Property(e => e.Po)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PO");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.ActCodeNavigation).WithMany(p => p.BankPaymentDs)
                .HasForeignKey(d => d.ActCode)
                .HasConstraintName("FK_BankPaymentD_Chart");

            entity.HasOne(d => d.Person).WithMany(p => p.BankPaymentDs)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_dbo.BankPaymentD_dbo.BBookM_PersonID");
        });

        modelBuilder.Entity<BankPaymentDview>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("BankPaymentDView");

            entity.Property(e => e.Accounts)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.BrecNo1).HasColumnName("BRecNo1");
            entity.Property(e => e.BrecNo2).HasColumnName("BRecNo2");
            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ChkDate).HasColumnType("datetime");
            entity.Property(e => e.CostCenterName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CostId).HasColumnName("CostID");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.ManualNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PersonId).HasColumnName("PersonID");
            entity.Property(e => e.Po)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PO");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<BankPaymentM>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.BankPaymentM");

            entity.ToTable("BankPaymentM");

            entity.Property(e => e.BrecNo1).HasColumnName("BRecNo1");
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BankPaymentM_CurrentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("BR")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BankPaymentM_InputType");
            entity.Property(e => e.Mcode)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BankPaymentM_MCode")
                .HasColumnName("MCode");
            entity.Property(e => e.Posted).HasAnnotation("Relational:DefaultConstraintName", "DF_BankPaymentM_IsActive");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Vdate)
                .HasColumnType("datetime")
                .HasColumnName("VDate");
            entity.Property(e => e.Voucher)
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasComputedColumnSql("(([inputtype]+'-')+right('000000'+CONVERT([varchar](6),[MCode]),(6)))", false);
            entity.Property(e => e.VoucherNo)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.BookCodeNavigation).WithMany(p => p.BankPaymentMs)
                .HasForeignKey(d => d.BookCode)
                .HasConstraintName("FK_BankPaymentM_Chart");

            entity.HasOne(d => d.Company).WithMany(p => p.BankPaymentMs)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BankPaymentM_Company");
        });

        modelBuilder.Entity<BankPaymentMview>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("BankPaymentMView");

            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.Book)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Mcode).HasColumnName("MCode");
            entity.Property(e => e.Po)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false)
                .HasColumnName("PO");
            entity.Property(e => e.Prefix)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Remarks)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Voucher)
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.VoucherNo).HasMaxLength(4000);
        });

        modelBuilder.Entity<BankPaymentView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("BankPaymentView");

            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.Book)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Mcode).HasColumnName("MCode");
            entity.Property(e => e.Po)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false)
                .HasColumnName("PO");
            entity.Property(e => e.Remarks)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Voucher)
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.VoucherNo).HasMaxLength(4000);
        });

        modelBuilder.Entity<BankReceiptD>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.BBookD");

            entity.ToTable("BankReceiptD");

            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.BrecNo1).HasColumnName("BRecNo1");
            entity.Property(e => e.BrecNo2).HasColumnName("BRecNo2");
            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ChkDate).HasColumnType("datetime");
            entity.Property(e => e.CostId).HasColumnName("CostID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BBookD_CreateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.ManualNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PersonId).HasColumnName("PersonID");
            entity.Property(e => e.Po)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PO");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.ActCodeNavigation).WithMany(p => p.BankReceiptDs)
                .HasForeignKey(d => d.ActCode)
                .HasConstraintName("FK_BBookD_Chart");

            entity.HasOne(d => d.Person).WithMany(p => p.BankReceiptDs)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_dbo.BBookD_dbo.BBookM_PersonID");
        });

        modelBuilder.Entity<BankReceiptDview>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("BankReceiptDView");

            entity.Property(e => e.Accounts)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.BrecNo1).HasColumnName("BRecNo1");
            entity.Property(e => e.BrecNo2).HasColumnName("BRecNo2");
            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ChkDate).HasColumnType("datetime");
            entity.Property(e => e.CostCenterName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CostId).HasColumnName("CostID");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.ManualNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PersonId).HasColumnName("PersonID");
            entity.Property(e => e.Po)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PO");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<BankReceiptM>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.BBookM");

            entity.ToTable("BankReceiptM");

            entity.Property(e => e.BrecNo1).HasColumnName("BRecNo1");
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BBookM_CurrentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("BR")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BBookM_InputType");
            entity.Property(e => e.Mcode)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BBookM_MCode")
                .HasColumnName("MCode");
            entity.Property(e => e.Posted).HasAnnotation("Relational:DefaultConstraintName", "DF_BBookM_IsActive");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Vdate)
                .HasColumnType("datetime")
                .HasColumnName("VDate");
            entity.Property(e => e.Voucher)
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasComputedColumnSql("(([inputtype]+'-')+right('000000'+CONVERT([varchar](6),[MCode]),(6)))", false);
            entity.Property(e => e.VoucherNo)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.BookCodeNavigation).WithMany(p => p.BankReceiptMs)
                .HasForeignKey(d => d.BookCode)
                .HasConstraintName("FK_BBookM_Chart");

            entity.HasOne(d => d.Company).WithMany(p => p.BankReceiptMs)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BBookM_Company");
        });

        modelBuilder.Entity<BankReceiptView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("BankReceiptView");

            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.Book)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Mcode).HasColumnName("MCode");
            entity.Property(e => e.Po)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false)
                .HasColumnName("PO");
            entity.Property(e => e.Remarks)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Voucher)
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.VoucherNo).HasMaxLength(4000);
        });

        modelBuilder.Entity<CashPaymentD>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.CashPaymentD");

            entity.ToTable("CashPaymentD");

            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.BrecNo1).HasColumnName("BRecNo1");
            entity.Property(e => e.BrecNo2).HasColumnName("BRecNo2");
            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ChkDate).HasColumnType("datetime");
            entity.Property(e => e.CostId).HasColumnName("CostID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CashPaymentD_CreateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.ManualNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PersonId).HasColumnName("PersonID");
            entity.Property(e => e.Po)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PO");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.ActCodeNavigation).WithMany(p => p.CashPaymentDs)
                .HasForeignKey(d => d.ActCode)
                .HasConstraintName("FK_CashPaymentD_Chart");

            entity.HasOne(d => d.Person).WithMany(p => p.CashPaymentDs)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_dbo.CashPaymentD_dbo.BBookM_PersonID");
        });

        modelBuilder.Entity<CashPaymentDview>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("CashPaymentDView");

            entity.Property(e => e.Accounts)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.BrecNo1).HasColumnName("BRecNo1");
            entity.Property(e => e.BrecNo2).HasColumnName("BRecNo2");
            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ChkDate).HasColumnType("datetime");
            entity.Property(e => e.CostCenterName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CostId).HasColumnName("CostID");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.ManualNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PersonId).HasColumnName("PersonID");
            entity.Property(e => e.Po)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PO");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<CashPaymentM>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.CashPaymentM");

            entity.ToTable("CashPaymentM");

            entity.Property(e => e.BrecNo1).HasColumnName("BRecNo1");
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CashPaymentM_CurrentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("BR")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CashPaymentM_InputType");
            entity.Property(e => e.Mcode)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CashPaymentM_MCode")
                .HasColumnName("MCode");
            entity.Property(e => e.Posted).HasAnnotation("Relational:DefaultConstraintName", "DF_CashPaymentM_IsActive");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Vdate)
                .HasColumnType("datetime")
                .HasColumnName("VDate");
            entity.Property(e => e.Voucher)
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasComputedColumnSql("(([inputtype]+'-')+right('000000'+CONVERT([varchar](6),[MCode]),(6)))", false);
            entity.Property(e => e.VoucherNo)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.BookCodeNavigation).WithMany(p => p.CashPaymentMs)
                .HasForeignKey(d => d.BookCode)
                .HasConstraintName("FK_CashPaymentM_Chart");

            entity.HasOne(d => d.Company).WithMany(p => p.CashPaymentMs)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CashPaymentM_Company");
        });

        modelBuilder.Entity<CashPaymentMview>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("CashPaymentMView");

            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.Book)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Mcode).HasColumnName("MCode");
            entity.Property(e => e.Po)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false)
                .HasColumnName("PO");
            entity.Property(e => e.Prefix)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Remarks)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Voucher)
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.VoucherNo).HasMaxLength(4000);
        });

        modelBuilder.Entity<CashReceiptD>(entity =>
        {
            entity.ToTable("CashReceiptD");

            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.CurrentDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(50);

            entity.HasOne(d => d.Ref).WithMany(p => p.CashReceiptDs)
                .HasForeignKey(d => d.RefId)
                .HasConstraintName("FK_CashReceiptD_CashReceiptM");
        });

        modelBuilder.Entity<CashReceiptDview>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("CashReceiptDView");

            entity.Property(e => e.AccountName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.Description).HasMaxLength(50);
        });

        modelBuilder.Entity<CashReceiptM>(entity =>
        {
            entity.ToTable("CashReceiptM");

            entity.Property(e => e.CurrentDate).HasColumnType("datetime");
            entity.Property(e => e.Date)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CashReceiptM_Date")
                .HasColumnType("datetime");
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.InputType)
                .IsRequired()
                .HasMaxLength(5)
                .HasDefaultValue("CR")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CashReceiptM_InputType");
            entity.Property(e => e.InvoiceNumber)
                .HasMaxLength(45)
                .HasComputedColumnSql("(((((([InputType]+'-')+CONVERT([varchar](4),datepart(year,[Date])))+right('0'+CONVERT([varchar](2),datepart(month,[Date])),(2)))+right('0'+CONVERT([varchar](2),datepart(day,[Date])),(2)))+'-')+CONVERT([varchar],[RefNo]))", false);
            entity.Property(e => e.PartyId).HasColumnName("PartyID");
            entity.Property(e => e.RefNo).HasAnnotation("Relational:DefaultConstraintName", "DF_CashReceiptM_RefNo");
            entity.Property(e => e.Subtotal)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CashReceiptM_Subtotal")
                .HasColumnType("money");
        });

        modelBuilder.Entity<CashReceiptMview>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("CashReceiptMView");

            entity.Property(e => e.Action).HasColumnName("action");
            entity.Property(e => e.Balance).HasColumnType("money");
            entity.Property(e => e.Clientname)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DueDate).HasColumnName("due_date");
            entity.Property(e => e.InvoiceNumber).HasMaxLength(45);
            entity.Property(e => e.Prefix)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Total).HasColumnType("money");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("Category");

            entity.HasIndex(e => e.Name, "IX_Category").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CosactId).HasColumnName("COSActID");
            entity.Property(e => e.Description).IsUnicode(false);
            entity.Property(e => e.InvactId).HasColumnName("INVActID");
            entity.Property(e => e.IsActive).HasAnnotation("Relational:DefaultConstraintName", "DF_Category_IsActive");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NatureId).HasColumnName("NatureID");
            entity.Property(e => e.SlactId).HasColumnName("SLActID");
            entity.Property(e => e.SlractId).HasColumnName("SLRActID");
            entity.Property(e => e.WipactId).HasColumnName("WIPActID");
        });

        modelBuilder.Entity<Chart>(entity =>
        {
            entity.ToTable("Chart");

            entity.Property(e => e.Address)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.CrDays).HasAnnotation("Relational:DefaultConstraintName", "DF_Chart_CrDays_1");
            entity.Property(e => e.Descript)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Fax)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Fstperc)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Chart_Fstperc")
                .HasColumnType("money");
            entity.Property(e => e.GroupId).HasColumnName("GroupID");
            entity.Property(e => e.Gstno)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("GSTNo");
            entity.Property(e => e.Gstperc)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Chart_Gstperc")
                .HasColumnType("money");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Name2)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NatureId).HasColumnName("NatureID");
            entity.Property(e => e.NatureName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Ntnno)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NTNNo");
            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SpersonId).HasColumnName("SPersonID");
            entity.Property(e => e.TypeId).HasColumnName("TypeID");
            entity.Property(e => e.TypeName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Whperc).HasColumnType("money");

            entity.HasOne(d => d.User).WithMany(p => p.Charts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Chart_Users");
        });

        modelBuilder.Entity<ChartActType>(entity =>
        {
            entity.HasKey(e => e.RefNo);

            entity.Property(e => e.RefNo).ValueGeneratedNever();
            entity.Property(e => e.Gptype).HasColumnName("GPType");
            entity.Property(e => e.HeaderName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.HeaderName2)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.ToTable("City");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<CityCountryView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("CityCountryView");

            entity.Property(e => e.City)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("city");
            entity.Property(e => e.Citystatus).HasColumnName("citystatus");
            entity.Property(e => e.Countryname)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("countryname");
            entity.Property(e => e.Countrystatus).HasColumnName("countrystatus");
            entity.Property(e => e.Id).HasColumnName("id");
        });

        modelBuilder.Entity<Company>(entity =>
        {
            entity.HasKey(e => e.Code);

            entity.ToTable("Company");

            entity.Property(e => e.Code).ValueGeneratedNever();
            entity.Property(e => e.Address)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.AgedColH1)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.AgedColH2)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.AgedColH3)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.AgedColH4)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Branch)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BranchPayId).HasColumnName("BranchPayID");
            entity.Property(e => e.BranchRecId).HasColumnName("BranchRecID");
            entity.Property(e => e.Company1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Company");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Fax)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Fbrauth)
                .IsUnicode(false)
                .HasColumnName("FBRAUTH");
            entity.Property(e => e.Fbrurl)
                .IsUnicode(false)
                .HasColumnName("FBRURL");
            entity.Property(e => e.Gstno)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("GSTNo");
            entity.Property(e => e.ManCode)
                .HasMaxLength(6)
                .IsUnicode(false)
                .HasComputedColumnSql("(right('000000'+CONVERT([varchar](6),[Code]),(6)))", false);
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Note).HasColumnType("text");
            entity.Property(e => e.Ntnno)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NTNNo");
            entity.Property(e => e.Phone)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Ploan).HasColumnName("PLoan");
            entity.Property(e => e.Posid).HasColumnName("POSID");
            entity.Property(e => e.Prefix)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.Rloan).HasColumnName("RLoan");
            entity.Property(e => e.StaxAccountId).HasColumnName("STaxAccountID");
            entity.Property(e => e.Usin)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("USIN");
            entity.Property(e => e.WgtaxAccountId).HasColumnName("WGTaxAccountID");
            entity.Property(e => e.WtaxAccountId).HasColumnName("WTaxAccountID");
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.ToTable("Country");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable("Customer");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Address1)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Address2)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Address3)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CityId).HasColumnName("CityID");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Fax)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IdentityNo)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Mobile)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Province)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Strno)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("STRNo");
            entity.Property(e => e.Website)
                .HasMaxLength(25)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Design>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Design__3214EC07C27C4859");

            entity.ToTable("Design");

            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.ModifiedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<DesignComponent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DesignCo__3214EC07E5AE57D5");

            entity.ToTable("DesignComponent");

            entity.Property(e => e.ComponentType).HasMaxLength(50);

            entity.HasOne(d => d.Design).WithMany(p => p.DesignComponents)
                .HasForeignKey(d => d.DesignId)
                .HasConstraintName("FK_DesignComponent_Design");
        });

        modelBuilder.Entity<Dropdown>(entity =>
        {
            entity.ToTable("Dropdown");

            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Account).WithMany(p => p.Dropdowns)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK_Dropdown_Chart");
        });

        modelBuilder.Entity<Dumpdatum>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("dumpdata");

            entity.Property(e => e.Value1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value1");
            entity.Property(e => e.Value10)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value10");
            entity.Property(e => e.Value11)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value11");
            entity.Property(e => e.Value12)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value12");
            entity.Property(e => e.Value13)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value13");
            entity.Property(e => e.Value2)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value2");
            entity.Property(e => e.Value3)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value3");
            entity.Property(e => e.Value4)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value4");
            entity.Property(e => e.Value5)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value5");
            entity.Property(e => e.Value6)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value6");
            entity.Property(e => e.Value7)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value7");
            entity.Property(e => e.Value8)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value8");
            entity.Property(e => e.Value9)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("value9");
        });

        modelBuilder.Entity<FormDatum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FormData__3214EC0741AD75C8");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FieldName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<FormDefinition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FormDefi__3214EC07A0F1E899");

            entity.Property(e => e.TableName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<FormField>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FormFiel__3214EC0781850C8D");

            entity.Property(e => e.DataType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FieldName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.LabelName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Form).WithMany(p => p.FormFields)
                .HasForeignKey(d => d.FormId)
                .HasConstraintName("FK__FormField__FormI__2B0A656D");
        });

        modelBuilder.Entity<Gjouranlview>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Gjouranlview");

            entity.Property(e => e.Accounts)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Book)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.Credit).HasColumnType("money");
            entity.Property(e => e.Ddate).HasColumnName("DDate");
            entity.Property(e => e.Debit).HasColumnType("money");
            entity.Property(e => e.InputType)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Mcode).HasColumnName("MCode");
            entity.Property(e => e.Mdate).HasColumnName("MDate");
            entity.Property(e => e.Remarks)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Voucher)
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.VoucherNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<GjournalD>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.GJournalD");

            entity.ToTable("GJournalD");

            entity.Property(e => e.Cheque)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ChkDate).HasColumnType("datetime");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_GJournalD_CreateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Credit).HasColumnType("money");
            entity.Property(e => e.Debit).HasColumnType("money");
            entity.Property(e => e.PersonId).HasColumnName("PersonID");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.ActCodeNavigation).WithMany(p => p.GjournalDs)
                .HasForeignKey(d => d.ActCode)
                .HasConstraintName("FK_GJournalD_Chart");

            entity.HasOne(d => d.Person).WithMany(p => p.GjournalDs)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_dbo.GJournalD_dbo.GJournalM_PersonID");
        });

        modelBuilder.Entity<GjournalM>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.GJournalM");

            entity.ToTable("GJournalM");

            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_GJournalM_CurrentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("GV")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_GJournalM_InputType");
            entity.Property(e => e.Mcode)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_GJournalM_MCode")
                .HasColumnName("MCode");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Vdate)
                .HasColumnType("datetime")
                .HasColumnName("VDate");
            entity.Property(e => e.Voucher)
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasComputedColumnSql("(([inputtype]+'-')+right('000000'+CONVERT([varchar](6),[MCode]),(6)))", false);
            entity.Property(e => e.VoucherNo)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.BookCodeNavigation).WithMany(p => p.GjournalMs)
                .HasForeignKey(d => d.BookCode)
                .HasConstraintName("FK_GJournalM_Chart");

            entity.HasOne(d => d.Company).WithMany(p => p.GjournalMs)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GJournalM_Company");
        });

        modelBuilder.Entity<IbbookEntry>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("IBBookEntry");

            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.ChqDate).HasColumnType("datetime");
            entity.Property(e => e.ChqNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CostRate).HasColumnType("money");
            entity.Property(e => e.Credit).HasColumnType("money");
            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_IBBookEntry_CurrentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Debit).HasColumnType("money");
            entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.InvoiceId).HasColumnName("InvoiceID");
            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.LoginId).HasColumnName("LoginID");
            entity.Property(e => e.Quantity).HasColumnType("money");
            entity.Property(e => e.SoseqNo).HasColumnName("SOSeqNo");
        });

        modelBuilder.Entity<IcbookEntry>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ICBookEntry");

            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.ChqDate).HasColumnType("datetime");
            entity.Property(e => e.ChqNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CostRate).HasColumnType("money");
            entity.Property(e => e.Credit).HasColumnType("money");
            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ICBookEntry_CurrentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Debit).HasColumnType("money");
            entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.InvoiceId).HasColumnName("InvoiceID");
            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.LoginId).HasColumnName("LoginID");
            entity.Property(e => e.Quantity).HasColumnType("money");
            entity.Property(e => e.SoseqNo).HasColumnName("SOSeqNo");
        });

        modelBuilder.Entity<IchequeReqEntry>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("IChequeReqEntry");

            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.ChqDate).HasColumnType("datetime");
            entity.Property(e => e.ChqNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CostRate).HasColumnType("money");
            entity.Property(e => e.Credit).HasColumnType("money");
            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_IChequeReqEntry_CurrentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Debit).HasColumnType("money");
            entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.InvoiceId).HasColumnName("InvoiceID");
            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.LoginId).HasColumnName("LoginID");
            entity.Property(e => e.Quantity).HasColumnType("money");
            entity.Property(e => e.SoseqNo).HasColumnName("SOSeqNo");
        });

        modelBuilder.Entity<IgmultiEntry>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("IGmultiEntry");

            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.ChqDate).HasColumnType("datetime");
            entity.Property(e => e.ChqNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CostRate).HasColumnType("money");
            entity.Property(e => e.Credit).HasColumnType("money");
            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_IGmultiEntry_CurrentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Debit).HasColumnType("money");
            entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.InvoiceId).HasColumnName("InvoiceID");
            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.LoginId).HasColumnName("LoginID");
            entity.Property(e => e.Quantity).HasColumnType("money");
            entity.Property(e => e.SoseqNo).HasColumnName("SOSeqNo");
        });

        modelBuilder.Entity<Item>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Item");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Hscode)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("HSCode");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Packing).HasColumnType("money");
            entity.Property(e => e.UnitId).HasColumnName("UnitID");
        });

        modelBuilder.Entity<Ledger>(entity =>
        {
            entity.HasKey(e => e.LedgerId).HasName("PK__Ledger__AE70E0CF50C41202");

            entity.ToTable("Ledger");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Credit).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Debit).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Narration)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.VoucherNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<MainMenu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MainMenu__3214EC07F0DB3740");

            entity.ToTable("MainMenu");

            entity.Property(e => e.CurrentDate).HasColumnType("datetime");
            entity.Property(e => e.Icon).HasMaxLength(255);
            entity.Property(e => e.Label).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Nameclass).HasMaxLength(255);
            entity.Property(e => e.Subname).HasMaxLength(255);
            entity.Property(e => e.Url).HasMaxLength(500);

            entity.HasOne(d => d.App).WithMany(p => p.MainMenus)
                .HasForeignKey(d => d.AppId)
                .HasConstraintName("FK__MainMenu__AppId__29971E47");
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.ToTable("menu");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Action)
                .HasMaxLength(50)
                .HasColumnName("action");
            entity.Property(e => e.Apiaction).HasMaxLength(50);
            entity.Property(e => e.Apicontroller).HasMaxLength(50);
            entity.Property(e => e.Controller)
                .HasMaxLength(50)
                .HasColumnName("controller");
            entity.Property(e => e.CreateMessage).IsUnicode(false);
            entity.Property(e => e.IsApi).HasAnnotation("Relational:DefaultConstraintName", "DF_menu_IsApi");
            entity.Property(e => e.Menuid).HasColumnName("menuid");
            entity.Property(e => e.Moduleid).HasColumnName("moduleid");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Nameclass)
                .HasMaxLength(200)
                .HasColumnName("nameclass");
            entity.Property(e => e.Namelink).HasColumnName("namelink");
            entity.Property(e => e.RemoveMessage).IsUnicode(false);
            entity.Property(e => e.Sort).HasColumnName("sort");
            entity.Property(e => e.Subnameclass)
                .HasMaxLength(100)
                .HasColumnName("subnameclass");
            entity.Property(e => e.Target).HasColumnName("target");
            entity.Property(e => e.UpdateMessage).IsUnicode(false);

            entity.HasOne(d => d.Module).WithMany(p => p.Menus)
                .HasForeignKey(d => d.Moduleid)
                .HasConstraintName("FK_menu_module");
        });

        modelBuilder.Entity<Module>(entity =>
        {
            entity.ToTable("module");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Icon)
                .HasMaxLength(200)
                .HasColumnName("icon");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Nameclass)
                .HasMaxLength(200)
                .HasColumnName("nameclass");
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.Seqno).HasColumnName("seqno");
            entity.Property(e => e.Subname)
                .HasMaxLength(200)
                .HasColumnName("subname");
            entity.Property(e => e.Url)
                .HasMaxLength(200)
                .HasColumnName("url");
        });

        modelBuilder.Entity<MyDatum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MyData__3214EC07D60B9C40");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name2).HasMaxLength(100);
        });

        modelBuilder.Entity<Operation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Operatio__3214EC07F6727354");

            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<PinvoiceD>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.PInvoiceD");

            entity.ToTable("PInvoiceD");

            entity.Property(e => e.Amount).HasComputedColumnSql("(round([Pcs]*[Rate],(0)))", false);
            entity.Property(e => e.BrandId).HasColumnName("BrandID");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.IrefId).HasColumnName("IRefID");
            entity.Property(e => e.IrefSeq).HasColumnName("IRefSeq");
            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.LessWhAmt).HasColumnType("money");
            entity.Property(e => e.LocationId).HasColumnName("LocationID");
            entity.Property(e => e.NetAmount).HasComputedColumnSql("(round(round([Quantity]*[Rate],(2))+round((round([Quantity]*[Rate],(2))*isnull([Tax],(2)))/(100),(2)),(0))-((round((round([Quantity]*[Rate],(2))*isnull([Tax],(0)))/(100),(2))*isnull([WHTax],(0)))/(100)+isnull([LessWhAmt],(0))))", false);
            entity.Property(e => e.Packing).HasColumnType("money");
            entity.Property(e => e.Pcs).HasColumnType("money");
            entity.Property(e => e.QualityId).HasColumnName("QualityID");
            entity.Property(e => e.Quantity).HasColumnType("money");
            entity.Property(e => e.RefId).HasColumnName("RefID");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.SizeId).HasColumnName("SizeID");
            entity.Property(e => e.Tax).HasColumnType("money");
            entity.Property(e => e.TaxAmount).HasComputedColumnSql("(round((round([Quantity]*[Rate],(2))*isnull([Tax],(0)))/(100),(2)))", false);
            entity.Property(e => e.Unit)
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.UnitId).HasColumnName("UnitID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.WhTaxAmount).HasComputedColumnSql("((round((round([Quantity]*[Rate],(2))*isnull([Tax],(0)))/(100),(2))*isnull([WHTax],(0)))/(100))", false);
            entity.Property(e => e.Whtax)
                .HasColumnType("money")
                .HasColumnName("WHTax");

            entity.HasOne(d => d.Ref).WithMany(p => p.PinvoiceDs)
                .HasForeignKey(d => d.RefId)
                .HasConstraintName("FK_PInvoiceD_PInvoiceM");
        });

        modelBuilder.Entity<PinvoiceM>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.PInvoiceM");

            entity.ToTable("PInvoiceM");

            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PInvoiceM_CreateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PInvoiceM_CurrentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Discount).HasColumnType("money");
            entity.Property(e => e.DrefNo)
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasComputedColumnSql("(([inputtype]+'-')+right('000000'+CONVERT([varchar](6),[RefNo]),(6)))", false)
                .HasColumnName("DRefNo");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Mwhtax)
                .HasColumnType("money")
                .HasColumnName("MWHTax");
            entity.Property(e => e.PartyId).HasColumnName("PartyID");
            entity.Property(e => e.PrefNo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("PRefNo");
            entity.Property(e => e.RefId).HasColumnName("RefID");
            entity.Property(e => e.RefNo).HasAnnotation("Relational:DefaultConstraintName", "DF_PInvoiceM_MCode");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Company).WithMany(p => p.PinvoiceMs)
                .HasForeignKey(d => d.CompanyId)
                .HasConstraintName("FK_PInvoiceM_Company");

            entity.HasOne(d => d.Party).WithMany(p => p.PinvoiceMs)
                .HasForeignKey(d => d.PartyId)
                .HasConstraintName("FK_PInvoiceM_Chart");

            entity.HasOne(d => d.User).WithMany(p => p.PinvoiceMs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_PInvoiceM_Users");
        });

        modelBuilder.Entity<PpinvoiceD>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.PPInvoiceD");

            entity.ToTable("PPInvoiceD");

            entity.Property(e => e.Amount)
                .HasComputedColumnSql("(round([Quantity]*[Rate],(2)))", false)
                .HasColumnType("money");
            entity.Property(e => e.BrandId).HasColumnName("BrandID");
            entity.Property(e => e.ComPerc).HasColumnType("money");
            entity.Property(e => e.CommAmt)
                .HasComputedColumnSql("(round((round([Quantity]*[Rate],(2))*isnull([ComPerc],(0)))/(100),(2)))", false)
                .HasColumnType("money");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.GstPerc).HasColumnType("money");
            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.LocationId).HasColumnName("LocationID");
            entity.Property(e => e.NetAmount)
                .HasComputedColumnSql("(round([Quantity]*[Rate],(2))+round((round([Quantity]*[Rate],(2))*isnull([ComPerc],(0)))/(100),(2)))", false)
                .HasColumnType("money");
            entity.Property(e => e.Packing).HasColumnType("money");
            entity.Property(e => e.Pcs).HasColumnType("money");
            entity.Property(e => e.QualityId).HasColumnName("QualityID");
            entity.Property(e => e.Quantity).HasColumnType("money");
            entity.Property(e => e.Rate).HasColumnType("money");
            entity.Property(e => e.RefId).HasColumnName("RefID");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.SizeId).HasColumnName("SizeID");
            entity.Property(e => e.Unit)
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Ref).WithMany(p => p.PpinvoiceDs)
                .HasForeignKey(d => d.RefId)
                .HasConstraintName("FK_dbo.PPInvoiceD_dbo.PPInvoiceM_RefID");
        });

        modelBuilder.Entity<PpinvoiceM>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.PPInvoiceM");

            entity.ToTable("PPInvoiceM");

            entity.Property(e => e.ChallanNo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CurrentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PPInvoiceM_CurrentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.DrefNo)
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasComputedColumnSql("(([inputtype]+'-')+right('000000'+CONVERT([varchar](6),[RefNo]),(6)))", false)
                .HasColumnName("DRefNo");
            entity.Property(e => e.InputType)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.PartyId).HasColumnName("PartyID");
            entity.Property(e => e.RefNo).HasAnnotation("Relational:DefaultConstraintName", "DF_PPInvoiceM_MCode");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Company).WithMany(p => p.PpinvoiceMs)
                .HasForeignKey(d => d.CompanyId)
                .HasConstraintName("FK_PPInvoiceM_Company");

            entity.HasOne(d => d.User).WithMany(p => p.PpinvoiceMs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_PPInvoiceM_Users");
        });

        modelBuilder.Entity<PublishedDesign>(entity =>
        {
            entity.ToTable("PublishedDesign");

            entity.Property(e => e.ElementsJson)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PublishedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.ReportKey).HasName("PK__Reports__0261CF2C5FB83704");

            entity.Property(e => e.ReportKey).HasMaxLength(50);
            entity.Property(e => e.Description).HasMaxLength(250);
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.StoredProcedure)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<RpttrialBalance>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_TrialBalanceData");

            entity.ToTable("RPTTrialBalance");

            entity.HasIndex(e => e.AccountName, "IX_TrialBalanceData").IsUnique();

            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ChqNo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ChqStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Credit)
                .HasDefaultValue(0.0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RPTTrialBalance_Debit1");
            entity.Property(e => e.CurrentDate).HasColumnType("datetime");
            entity.Property(e => e.Debit)
                .HasDefaultValue(0.0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RPTTrialBalance_Debit");
            entity.Property(e => e.Description).IsUnicode(false);
            entity.Property(e => e.Description2).IsUnicode(false);
            entity.Property(e => e.DispDivisionName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.FlockId).HasColumnName("FlockID");
            entity.Property(e => e.FlockName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.GroupId).HasColumnName("GroupID");
            entity.Property(e => e.GroupName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.InputType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ItemName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.OppName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ReferenceNo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VehicleNo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VoucherNo)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<SaleInvoiceDetail>(entity =>
        {
            entity.ToTable("Sale_Invoice_Detail");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Amount)
                .HasComputedColumnSql("(([Package]*[Packing])*[Rate])", false)
                .HasColumnType("money");
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.NetAmount)
                .HasComputedColumnSql("(([Package]*[Packing])*[Rate]+((([Package]*[Packing])*[Rate])*[Tax])/(100))", false)
                .HasColumnType("money");
            entity.Property(e => e.Package).HasColumnType("money");
            entity.Property(e => e.Packing).HasColumnType("money");
            entity.Property(e => e.Quantity)
                .HasComputedColumnSql("([Package]*[Packing])", false)
                .HasColumnType("money");
            entity.Property(e => e.Rate).HasColumnType("money");
            entity.Property(e => e.Refid).HasColumnName("refid");
            entity.Property(e => e.Tax).HasColumnType("money");
            entity.Property(e => e.TaxAmount)
                .HasComputedColumnSql("(((([Package]*[Packing])*[Rate])*[Tax])/(100))", false)
                .HasColumnType("money");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Ref).WithMany(p => p.SaleInvoiceDetails)
                .HasForeignKey(d => d.Refid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Sale_Invoice_Detail_Sale_Invoice_Master");
        });

        modelBuilder.Entity<SaleInvoiceDetailView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SaleInvoiceDetailView");

            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.ItemName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NetAmount).HasColumnType("money");
            entity.Property(e => e.Package).HasColumnType("money");
            entity.Property(e => e.Packing).HasColumnType("money");
            entity.Property(e => e.Quantity).HasColumnType("money");
            entity.Property(e => e.Rate).HasColumnType("money");
            entity.Property(e => e.Refid).HasColumnName("refid");
            entity.Property(e => e.Tax).HasColumnType("money");
            entity.Property(e => e.TaxAmount).HasColumnType("money");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<SaleInvoiceMaster>(entity =>
        {
            entity.ToTable("Sale_Invoice_Master");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Fbrinvoice)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("FBRInvoice");
            entity.Property(e => e.Fbrqrcode).HasColumnName("FBRQRCode");
            entity.Property(e => e.RefernceNo)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<SaleInvoiceMasterView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SaleInvoiceMasterView");

            entity.Property(e => e.Company)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false);
            entity.Property(e => e.Customer)
                .IsRequired()
                .HasMaxLength(101)
                .IsUnicode(false);
            entity.Property(e => e.Fbrinvoice)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("fbrinvoice");
            entity.Property(e => e.Fbrqrcode).HasColumnName("fbrqrcode");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Mdate).HasColumnName("MDate");
            entity.Property(e => e.RefernceNo)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.TotalAmount).HasColumnType("money");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Saleinvoice2>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SALEINVO__3214EC07920CFF9A");

            entity.ToTable("SALEINVOICE2");

            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__service__3214EC0739E97CFE");

            entity.ToTable("service");

            entity.Property(e => e.Customername)
                .HasMaxLength(255)
                .HasColumnName("customername");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<Setting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__settings__3213E83F8A9CDD3B");

            entity.ToTable("settings");

            entity.HasIndex(e => e.SettingName, "UQ__settings__9C01CC5A984628D2").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.SettingName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("setting_name");
            entity.Property(e => e.SettingValue)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("setting_value");
        });

        modelBuilder.Entity<TrialBalance>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("TrialBalance");

            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.AdjWt).HasColumnType("money");
            entity.Property(e => e.AvgWt).HasColumnType("money");
            entity.Property(e => e.ChqNo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ChqStatus)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Credit).HasColumnType("money");
            entity.Property(e => e.CurrentDate).HasColumnType("datetime");
            entity.Property(e => e.Debit)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_TrialBalance_IsActive")
                .HasColumnType("money");
            entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");
            entity.Property(e => e.DepartmentName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Description).IsUnicode(false);
            entity.Property(e => e.Description2).IsUnicode(false);
            entity.Property(e => e.Division)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.FlockId).HasColumnName("FlockID");
            entity.Property(e => e.FlockName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.GrossWt).HasColumnType("money");
            entity.Property(e => e.GroupId).HasColumnName("GroupID");
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.InputType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ItemName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Less).HasColumnType("money");
            entity.Property(e => e.NetWt).HasColumnType("money");
            entity.Property(e => e.OppName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Pcs).HasColumnType("money");
            entity.Property(e => e.Quantity).HasColumnType("money");
            entity.Property(e => e.Rate).HasColumnType("money");
            entity.Property(e => e.VehicleNo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VoucherNo)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__unit__3214EC07952F0943");

            entity.ToTable("unit");

            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C797E917B");

            entity.Property(e => e.Creatdate).HasColumnType("datetime");
            entity.Property(e => e.CreateUser).HasMaxLength(100);
            entity.Property(e => e.Password).HasMaxLength(100);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.TypeId).HasColumnName("TypeID");
            entity.Property(e => e.UserEmail).HasMaxLength(100);
            entity.Property(e => e.UserName).HasMaxLength(100);
        });

        modelBuilder.Entity<UserReportView>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserRepo__3214EC075F776123");

            entity.HasIndex(e => new { e.UserId, e.ReportKey, e.ViewName }, "UK_UserReportView").IsUnique();

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsFavorite).HasDefaultValue(true);
            entity.Property(e => e.ReportKey)
                .IsRequired()
                .HasMaxLength(100)
                .HasDefaultValue("OpeningMaster");
            entity.Property(e => e.ViewName)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.ToTable("UserRole");

            entity.Property(e => e.Iconclass).HasMaxLength(50);
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<UsersBackup>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK_Users");

            entity.ToTable("Users_Backup");

            entity.HasIndex(e => e.UserName, "IX_Users").IsUnique();

            entity.Property(e => e.Creatdate).HasColumnType("datetime");
            entity.Property(e => e.CreateUser)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsAdmin).HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsAdmin");
            entity.Property(e => e.Password)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TypeId).HasColumnName("TypeID");
            entity.Property(e => e.UserEmail)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Type).WithMany(p => p.UsersBackups)
                .HasForeignKey(d => d.TypeId)
                .HasConstraintName("FK_Users_UserRole");
        });

        modelBuilder.Entity<UsersDetail>(entity =>
        {
            entity.ToTable("UsersDetail");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<ViewMonthlyExpense>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("View_MonthlyExpense");

            entity.Property(e => e.MonthName)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ViewMonthlyProfit>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("View_MonthlyProfit");

            entity.Property(e => e.MonthName)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ViewMonthlyRevenue>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("View_MonthlyRevenue");

            entity.Property(e => e.MonthName)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VwTotalRevenue>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_TotalRevenue");

            entity.Property(e => e.MonthName)
                .HasMaxLength(3)
                .IsUnicode(false);
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}