// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Initial.Models
{
    public partial class getdumpdataofflineResult
    {
        public string CustomerID { get; set; }
        public string ProductID { get; set; }
        public string UserID { get; set; }
        public int? IllegallyLock { get; set; }
        public string IServer { get; set; }
        public string IDatabase { get; set; }
        public string ILoginID { get; set; }
        public string IPassword { get; set; }
        public string ServerName { get; set; }
        public string HostID { get; set; }
        public short? DatabaseID { get; set; }
        public string DatabaseCount { get; set; }
        public DateTime? TerminationDate { get; set; }
        public DateTime? TerminationEnd { get; set; }
        public int? TerminationLock { get; set; }
    }
}
